"""experiments/b2-psi-probe/run.py (PLAN-v4 B2, with E0h): the pure pieces on
hand-built inputs, and the model side on a tiny untrained model. No checkpoint and
no document of FIT_TRAIN / FIT_VAL / EVAL at S = 48 is generated or read here; the
tiny fixtures generate a handful of S = 12 documents **by id** only where a range
guard needs an id inside a range, and never run a fit or an arm on the real model.

Governing text: experiments/b2-psi-probe/PREREG.md -- the base (e5ab398),
Amendment 1 (2ec60dd, which wins), the B0 addendum (99a6626).
"""

from __future__ import annotations

import ast
import hashlib
import importlib.util
import inspect
import json
import math
import random
import sys
from pathlib import Path

import pytest
import torch

from rsr.baselines.fifo import FIFOPolicy
from rsr.baselines.random_policy import RandomPolicy
from rsr.data.synthetic import (
    SyntheticConfig,
    _generate_document,
    discounted_demand,
    generate,
)
from rsr.metrics.headroom import simulate
from rsr.model.tg import TGConfig, TGModel
from rsr.model.tg.policy_loop import run_policy_loop
from rsr.retention.policy import MemoryState
from rsr.train.loop import build_vocab, encode

ROOT = Path(__file__).resolve().parents[1]
RUN = ROOT / "experiments" / "b2-psi-probe" / "run.py"
NAN = float("nan")


@pytest.fixture(scope="module")
def b2():
    spec = importlib.util.spec_from_file_location("b2_psi_probe_run", RUN)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["b2_psi_probe_run"] = mod
    spec.loader.exec_module(mod)
    return mod


# --------------------------------------------------------------------------- #
# tiny fixtures: S = 12, M = 4, D = 8 (p = 80), documents generated by id
# --------------------------------------------------------------------------- #

TS, TM, TL, TD = 12, 4, 16, 8


def _tiny_cfg(seed: int = 0) -> SyntheticConfig:
    return SyntheticConfig(
        sentences_per_document=TS, max_gap=8, heavy_tail_min=5, seed=seed
    )


def _tiny_docs(ids):
    return [_generate_document(i, _tiny_cfg()) for i in ids]


@pytest.fixture(scope="module")
def tiny():
    """A tiny untrained model and documents with ids inside B2's ranges."""
    train = _tiny_docs(range(920000, 920004))
    val = _tiny_docs(range(936000, 936003))
    ev = _tiny_docs(range(940000, 940002))
    vmap = build_vocab(train + val + ev)
    torch.manual_seed(0)
    cfg = TGConfig(
        D=TD, V=4 + len(vmap), F=22, max_sentence_tokens=TL,
        max_sentences_in_short_term=TM, pad_id=0, bos_id=1, eos_id=2, eod_id=3,
    )  # fmt: skip
    model = TGModel(cfg).eval()
    return {"model": model, "vmap": vmap, "train": train, "val": val, "eval": ev}


@pytest.fixture(scope="module")
def caps(b2, tiny):
    kw = {"vmap": tiny["vmap"], "S": TS, "m": TM, "L": TL}
    return {
        "train": [b2.capture_doc(tiny["model"], d, **kw) for d in tiny["train"]],
        "val": [b2.capture_doc(tiny["model"], d, **kw) for d in tiny["val"]],
        "eval": [b2.capture_doc(tiny["model"], d, **kw) for d in tiny["eval"]],
    }


def _state(gestalts, written_at, step):
    n = gestalts.shape[0]
    return MemoryState(
        gestalts=gestalts,
        written_at=torch.as_tensor(written_at, dtype=torch.long),
        live=torch.ones(n, dtype=torch.bool),
        step=step,
    )


# --------------------------------------------------------------------------- #
# §3 / A1.15: ranges, disjointness, aliasing, the guard
# --------------------------------------------------------------------------- #


def test_the_ranges_are_the_preregs(b2):
    assert b2.RANGES == {
        "FIT_TRAIN": (920000, 936000),
        "FIT_VAL": (936000, 937024),
        "EVAL": (940000, 980000),
    }
    assert b2.E0D_RESERVED == (900000, 920000)
    assert b2.USED_RANGES["E0d_A1"] == (262144, 263168)


def test_the_ranges_are_mutually_disjoint_and_clear_every_used_range(b2):
    assert b2.range_problems() == []


def test_an_overlap_with_any_used_range_is_a_problem(b2):
    used = {**b2.USED_RANGES, "planted": (936500, 936600)}
    probs = b2.range_problems(used=used)
    assert any("planted" in p and "FIT_VAL" in p for p in probs), probs
    probs = b2.range_problems(used={**b2.USED_RANGES, "e0d_like": (262144, 263168)})
    assert probs == []  # E0d's own range does not overlap B2's
    ranges = {**b2.RANGES, "EVAL": (262000, 263000)}
    assert any("E0d_A1" in p for p in b2.range_problems(ranges=ranges))


def test_b2_ranges_overlapping_each_other_or_e0ds_reservation_is_a_problem(b2):
    ranges = {**b2.RANGES, "FIT_VAL": (935000, 937024)}
    assert any("FIT_TRAIN" in p and "FIT_VAL" in p for p in b2.range_problems(ranges))
    ranges = {**b2.RANGES, "FIT_TRAIN": (910000, 936000)}
    assert any("E0D_RESERVED" in p for p in b2.range_problems(ranges))


def test_generator_seeds_do_not_alias_across_seeds(b2):
    assert b2.aliasing_problems() == []
    # an id past 1_000_003 aliases the next seed's low ids
    ranges = {**b2.RANGES, "EVAL": (1_000_000, 1_000_010)}
    assert b2.aliasing_problems(ranges=ranges) != []


def test_the_range_guard_refuses_an_id_outside_its_range(b2):
    b2.require_range([936000, 937023], "FIT_VAL")
    with pytest.raises(b2.RangeError):
        b2.require_range([936000, 940000], "FIT_VAL")
    with pytest.raises(b2.RangeError):
        b2.require_range([], "FIT_VAL")


def test_documents_by_id_are_the_generators_documents(b2):
    docs = generate(SyntheticConfig(sentences_per_document=48, seed=1, n_documents=3))
    for d in docs:
        assert b2.doc_by_id(1, d.doc_id) == d


def test_vocabulary_closure_reports_a_missing_word(b2, tiny):
    ok = b2.vocabulary_closure(tiny["train"], tiny["vmap"])
    assert ok["ok"] and ok["n_missing"] == 0
    vmap = dict(tiny["vmap"])
    vmap.pop(sorted(vmap)[0])
    assert not b2.vocabulary_closure(tiny["train"], vmap)["ok"]


# --------------------------------------------------------------------------- #
# §6: p, N_F, row counts
# --------------------------------------------------------------------------- #


def test_p_and_n_f_follow_the_amended_rule(b2):
    assert b2.p_of(128) == 16640
    assert b2.n_f(16640) == 264  # A1.15: ceil(10 p / 632)
    assert b2.u_rows(48) == 1128
    assert b2.c_rows(48, 16) == 632
    assert b2.N_E is None  # TBD-3: written by diff only before EVAL


# --------------------------------------------------------------------------- #
# §4: the feature maps and ProbeArgminPolicy
# --------------------------------------------------------------------------- #


def test_bilinear_features_are_vec_s_c_then_s_then_c(b2):
    s = torch.tensor([[1.0, 2.0]])
    c = torch.tensor([[3.0, 5.0]])
    f = b2.bilinear_features(s, c)
    assert f.dtype == torch.float64
    assert f.tolist() == [[3.0, 5.0, 6.0, 10.0, 1.0, 2.0, 3.0, 5.0]]
    w = torch.randn(8, dtype=torch.float64)
    W = w[:4].reshape(2, 2)
    manual = s.double() @ W @ c.double().T + w[4:6] @ s.double().T + w[6:] @ c.double().T
    assert torch.allclose(f @ w, manual.flatten())


def test_the_feature_builder_takes_s_and_c_and_nothing_else(b2):
    assert list(inspect.signature(b2.bilinear_features).parameters) == ["s_i", "c_t"]


def test_age_features_are_one_hot_on_one_to_s_minus_one(b2):
    f = b2.age_features(torch.tensor([1, 3, 11]), 12)
    assert f.shape == (3, 11) and f.dtype == torch.float64
    assert f.argmax(1).tolist() == [0, 2, 10] and f.sum().item() == 3.0
    with pytest.raises(ValueError):
        b2.age_features(torch.tensor([0]), 12)


def test_no_age_in_psi_hat_permuting_written_at_and_step_changes_nothing(b2):
    """§11 control 9: with the gestalts held fixed, ψ̂ does not move when
    written_at and the step are permuted."""
    torch.manual_seed(1)
    d = 3
    g = torch.randn(5, d)
    c = torch.randn(d)
    w = torch.randn(b2.p_of(d), dtype=torch.float64)
    doc = _tiny_docs([940000])[0]
    pol = b2.ProbeArgminPolicy(w, "bilinear", doc=doc, model_seed=0, arm="U", S=TS)
    a = pol.scores(_state(g, [2, 3, 4, 5, 6], 7), c, 7)
    b = pol.scores(_state(g, [6, 2, 5, 3, 4], 11), c, 11)
    assert torch.equal(a, b)
    assert b2.no_age_check(pol, g, c) is True


def test_the_probe_evicts_the_argmin_ties_to_the_oldest_and_logs_it(b2):
    doc = _tiny_docs([940000])[0]
    d = 2
    # w picks psi = u_s . s with u_s = (1, 0): scores are the first coordinate
    w = torch.zeros(b2.p_of(d), dtype=torch.float64)
    w[d * d] = 1.0
    pol = b2.ProbeArgminPolicy(w, "bilinear", doc=doc, model_seed=2, arm="U", S=TS)
    g = torch.tensor([[0.5, 0.0], [0.1, 9.0], [0.1, -9.0], [0.7, 0.0]])
    st = _state(g, [3, 4, 5, 6], 7)
    k = pol.select_eviction(st, torch.zeros(d), 7)
    assert k == 1  # 0.1 twice: the lower slot index
    rec = pol.log[-1]
    assert rec["victim_slot"] == 1 and rec["written_at"] == 4 and rec["age"] == 3
    assert rec["rank"] == 2 and rec["rank_shift"] == [2, 1]
    assert rec["margin"] == pytest.approx(0.0)
    assert rec["psi"] == pytest.approx([0.5, 0.1, 0.1, 0.7])
    assert rec["doc"] == doc.doc_id and rec["seed"] == 2 and rec["arm"] == "U"
    assert rec["kind"] in ("assert", "query", "filler")


def test_the_age_arm_reads_age_and_nothing_else(b2):
    doc = _tiny_docs([940000])[0]
    w = torch.zeros(TS - 1, dtype=torch.float64)
    w[2] = -1.0  # age 3 scores lowest
    pol = b2.ProbeArgminPolicy(w, "age", doc=doc, model_seed=0, arm="age_U", S=TS)
    st = _state(torch.zeros(4, 2), [3, 4, 5, 6], 7)
    assert pol.select_eviction(st, torch.zeros(2), 7) == 1  # written 4 -> age 3


def test_the_probe_policy_is_not_rsrpolicy_and_nothing_is_recorded(b2):
    src = RUN.read_text()
    tree = ast.parse(src)
    mods = {
        n.module for n in ast.walk(tree) if isinstance(n, ast.ImportFrom) and n.module
    }
    assert "rsr.retention.rsr" not in mods
    assert "RSRPolicy" not in src.replace("not `RSRPolicy`", "")
    calls = {
        n.func.attr
        for n in ast.walk(tree)
        if isinstance(n, ast.Call) and isinstance(n.func, ast.Attribute)
    }
    assert "record" not in calls and "from_registry" not in calls
    assert not hasattr(b2.ProbeArgminPolicy, "b") and not hasattr(b2, "nu")


# --------------------------------------------------------------------------- #
# §5: capture, stop-grad, probes, targets
# --------------------------------------------------------------------------- #


def test_stopgrad_cuts_the_graph(b2):
    x = torch.randn(3, requires_grad=True)
    y = b2._stopgrad(x * 2)
    assert not y.requires_grad and y.grad_fn is None


def test_captured_s_and_c_are_stop_grad_and_nothing_reaches_the_model(b2, tiny):
    model = tiny["model"]
    with torch.enable_grad():
        cap = b2.capture_doc(
            model, tiny["train"][0], vmap=tiny["vmap"], S=TS, m=TM, L=TL
        )
    for t in (cap.gest, cap.ctx):
        assert not t.requires_grad and t.grad_fn is None
    assert all(p.grad is None for p in model.parameters())
    # s_i is the gestalt the FIFO rollout wrote for sentence i, which is step i's srep
    assert torch.equal(cap.gest, cap.ctx)


def test_the_capture_fills_every_row_and_every_control_holds(b2, caps):
    for cap in caps["train"]:
        for r in b2.RANKS:
            D = cap.D[r]
            for t in range(1, TS):
                assert not torch.isnan(D[t, :t]).any(), (r, t)
            assert cap.identity_worst[r] <= b2.IDENTITY_TOL
        assert cap.sum_worst <= b2.SUM_TOL
        # resident sentences are FIFO's own r at every rank
        for r in (1, 2, 3):
            res = cap.resident
            assert torch.equal(cap.D[r][res], cap.D[0][res])


def test_row_counts_are_u_and_c(b2, caps):
    cap = caps["train"][0]
    t, i = b2.row_index(cap, "U", TM)
    assert len(t) == b2.u_rows(TS) and bool((i < t).all())
    t, i = b2.row_index(cap, "C", TM)
    assert len(t) == b2.c_rows(TS, TM)
    assert bool(cap.resident[t, i].all())


def test_probes_never_feed_back_into_the_fifo_rollout(b2, tiny, caps):
    """The capture's own FIFO answers equal a plain FIFO rollout's."""
    doc = tiny["train"][0]
    plain = b2.run_arm(
        tiny["model"], doc, b2.Logged(FIFOPolicy(), doc=doc, model_seed=0, arm="fifo"),
        vmap=tiny["vmap"], S=TS, m=TM, L=TL,
    )  # fmt: skip
    assert caps["train"][0].answers == plain["answers"]


def test_a_rank_r_probe_reads_the_swapped_in_sentence_at_rank_r(b2, tiny, caps):
    """One evicted sentence at one step, recomputed by hand at rank 2."""
    cap = caps["train"][1]
    t, i, r = TS - 1, 0, 2
    val = b2.probe_by_hand(
        tiny["model"], tiny["train"][1], cap, t, i, r, vmap=tiny["vmap"], m=TM, L=TL
    )
    assert cap.D[r][t, i].item() == pytest.approx(val, abs=1e-6)


def test_returns_start_at_k0_and_the_shifted_companion_starts_at_k1(b2):
    X = torch.tensor(
        [[NAN, NAN, NAN], [1.0, NAN, NAN], [2.0, 4.0, NAN]], dtype=torch.float64
    )
    G = b2.returns(X, 0.5)
    assert G[1, 0] == pytest.approx(1 + 0.5 * 2) and G[2, 1] == pytest.approx(4.0)
    Gp = b2.shifted(G)
    assert Gp[1, 0] == pytest.approx(2.0)  # sum_{k>=1} g^{k-1} X[t+k]
    assert Gp[2, 0] == 0.0 and Gp[2, 1] == 0.0  # t = S-1: empty sum
    assert math.isnan(Gp[0, 0])
    G0 = b2.returns(X, 0.0)
    assert torch.equal(b2.shifted(G0)[1, :1], X[2, :1])  # gamma 0: X[t+1]


def test_the_censored_target_is_zero_after_fifo_evicts(b2, caps):
    cap = caps["train"][0]
    lit = b2.literal(cap.D[0], cap.resident)
    t = TS - 1
    assert lit[t, 0] == 0.0 and not bool(cap.resident[t, 0])
    assert lit[t, t - 1] == cap.D[0][t, t - 1]


def test_target_matrices_by_arm(b2, caps):
    cap = caps["train"][0]
    U = b2.target_matrix(cap, "U", 0.9)
    assert torch.allclose(U, b2.returns(cap.D[0], 0.9), equal_nan=True)
    U2 = b2.target_matrix(cap, "U2", 0.9)
    assert torch.allclose(U2, b2.returns(cap.D[2], 0.9), equal_nan=True)
    Cp = b2.target_matrix(cap, "C+", 0.0)
    lit = b2.literal(cap.D[0], cap.resident)
    assert torch.allclose(Cp[1:-1], torch.nan_to_num(lit[2:], nan=0.0).where(
        ~torch.isnan(lit[1:-1]), torch.tensor(NAN, dtype=torch.float64)
    ), equal_nan=True)  # fmt: skip
    A = b2.target_matrix(cap, "age", None)
    assert A[5, 2] == 3.0


# --------------------------------------------------------------------------- #
# §6 / A1.6 / A1.7: the ridge
# --------------------------------------------------------------------------- #


def _ridge_problem(n=200, p=6, seed=0):
    g = torch.Generator().manual_seed(seed)
    X = torch.randn(n, p, generator=g, dtype=torch.float64)
    y = X @ torch.randn(p, generator=g, dtype=torch.float64)
    return X, y


def test_the_spectral_ridge_solves_the_normal_equations(b2):
    X, y = _ridge_problem()
    G = b2.Gram(X.shape[1], 1)
    G.add(X[:100], y[:100, None])
    G.add(X[100:], y[100:, None])
    assert torch.allclose(G.xtx, X.T @ X) and G.n == 200
    path = b2.solve_path(G.xtx, G.xty[:, 0], b2.LAMBDAS)
    for pt in path:
        lam_eff = pt["lam"] * float(torch.trace(G.xtx)) / X.shape[1]
        assert pt["lam_eff"] == pytest.approx(lam_eff)
        ref = torch.linalg.solve(G.xtx + lam_eff * torch.eye(6, dtype=torch.float64),
                                 G.xty[:, 0])  # fmt: skip
        assert torch.allclose(pt["w"], ref, atol=1e-8)
        assert pt["resid"] <= 1e-8 and pt["eligible"]


def test_the_gram_refuses_a_tensor_that_carries_graph(b2):
    G = b2.Gram(2, 1)
    with pytest.raises(ValueError, match="stop-grad"):
        G.add(torch.randn(3, 2, dtype=torch.float64, requires_grad=True),
              torch.zeros(3, 1, dtype=torch.float64))  # fmt: skip


def test_lambda_selection_takes_the_min_ties_to_the_larger_and_only_eligible(b2):
    path = [
        {"lam": 1e-2, "resid": 1e-12, "eligible": True},
        {"lam": 1e-1, "resid": 1e-12, "eligible": True},
        {"lam": 1.0, "resid": 1e-12, "eligible": True},
    ]
    assert b2.select_lambda(path, [0.5, 0.2, 0.2]) == 2  # tie -> larger lambda
    path[0]["eligible"], path[0]["resid"] = False, 1e-5
    assert b2.select_lambda(path, [0.1, 0.2, 0.3]) == 1  # ineligible skipped


def test_a_selected_lambda_over_1e8_residual_or_no_eligible_point_exits_1(b2):
    path = [
        {"lam": 1e-2, "resid": 5e-8, "eligible": True},
        {"lam": 1.0, "resid": 1e-12, "eligible": True},
    ]
    with pytest.raises(b2.RidgeFailure, match="1e-08"):
        b2.select_lambda(path, [0.1, 0.2])
    for p in path:
        p["eligible"] = False
    with pytest.raises(b2.RidgeFailure, match="no eligible"):
        b2.select_lambda(path, [0.1, 0.2])
    assert b2.RidgeFailure.exit_code == 1


def test_within_step_demeaning_removes_a_per_step_offset(b2):
    v = torch.tensor([1.0, 3.0, 10.0, 14.0], dtype=torch.float64)
    g = torch.tensor([0, 0, 1, 1])
    assert b2.within_step_demean(v, g).tolist() == [-1.0, 1.0, -2.0, 2.0]


def test_lambda_is_chosen_on_fit_val_and_never_on_eval(b2, caps):
    """A1.7: the fit's lambda comes from FIT_VAL rows. Handing it EVAL's rows is
    a range error, not a quietly different lambda."""
    fit = b2.fit_heads(caps["train"], caps["val"], "C", "bilinear", [("C", 0.9)], m=TM)
    assert fit[("C", 0.9)]["val_range"] == "FIT_VAL"
    with pytest.raises(b2.RangeError):
        b2.fit_heads(caps["train"], caps["eval"], "C", "bilinear", [("C", 0.9)], m=TM)
    with pytest.raises(b2.RangeError):
        b2.fit_heads(caps["val"], caps["val"], "C", "bilinear", [("C", 0.9)], m=TM)


def test_the_fit_selects_on_demeaned_val_mse_and_reports_raw(b2, caps):
    fit = b2.fit_heads(
        caps["train"], caps["val"], "U", "bilinear", [("U", 0.9), ("U+", 0.0)], m=TM
    )
    for key, f in fit.items():
        k = f["selected"]
        dm = f["val_mse_demeaned"]
        assert dm[k] == min(x for x, p in zip(dm, f["path"], strict=True)
                            if p["eligible"])  # fmt: skip
        assert len(f["val_mse_raw"]) == len(b2.LAMBDAS)
        assert f["w"].dtype == torch.float64 and f["w"].shape == (b2.p_of(TD),)
        assert f["path"][k]["resid"] <= b2.SELECTED_RESID


def test_the_age_head_fits_one_hot_age_with_the_same_rule(b2, caps):
    fit = b2.fit_heads(caps["train"], caps["val"], "C", "age", [("C", 0.9)], m=TM)
    assert fit[("C", 0.9)]["w"].shape == (TS - 1,)


def test_age_decodability_is_raw_mse_lambda_and_r2_on_fit_val(b2, caps):
    out = b2.age_decodability(caps["train"], caps["val"], "U", m=TM)
    assert out["lambda_rule"] == "raw_val_mse" and out["val_range"] == "FIT_VAL"
    assert out["r2"] <= 1.0


# --------------------------------------------------------------------------- #
# §6 / A1.10: the kind-oracle
# --------------------------------------------------------------------------- #


def test_class_means_use_fit_train_u_rows_at_full_memory(b2, caps):
    m = b2.class_means(caps["train"], 0.9, m=TM)
    assert set(m) <= {"assert", "query", "filler"}
    # by hand
    vals: dict[str, list[float]] = {}
    for cap in caps["train"]:
        G = b2.target_matrix(cap, "U", 0.9)
        for t in range(TM, TS):
            for i in range(t):
                vals.setdefault(cap.kinds[i], []).append(float(G[t, i]))
    for k, v in vals.items():
        assert m[k] == pytest.approx(sum(v) / len(v))
    with pytest.raises(b2.RangeError):
        b2.class_means(caps["val"], 0.9, m=TM)


def test_kind_oracle_ties_are_uniform_random_seeded_per_step(b2):
    """A1.10: ties inside the lowest class are broken by
    random.Random(f"ko:{seed}:{doc_id}:{t}"), never by age."""
    doc = _tiny_docs([940001])[0]
    means = {"assert": 1.0, "query": 1.0, "filler": 1.0}  # everything ties
    picks = []
    for t in range(20, 60):
        pol = b2.KindOracle(means, doc=doc, model_seed=1, tie="random", S=TS)
        st = MemoryState(
            gestalts=torch.zeros(4, 1),
            written_at=torch.tensor([0, 1, 2, 3]),
            live=torch.ones(4, dtype=torch.bool),
            step=t,
        )
        k = pol.select_eviction(st, torch.zeros(1), t)
        rng = random.Random(f"ko:1:{doc.doc_id}:{t}")
        assert k == rng.choice([0, 1, 2, 3])
        picks.append(k)
    assert len(set(picks)) > 1  # not the oldest every time
    old = b2.KindOracle(means, doc=doc, model_seed=1, tie="oldest", S=TS)
    assert old.select_eviction(st, torch.zeros(1), 30) == 0


def test_kind_oracle_evicts_the_lowest_class(b2):
    doc = _tiny_docs([940001])[0]
    kinds = [s.kind for s in doc.sentences]
    means = {"assert": 3.0, "query": 2.0, "filler": 1.0}
    pol = b2.KindOracle(means, doc=doc, model_seed=0, tie="random", S=TS)
    idx = list(range(4))
    st = MemoryState(gestalts=torch.zeros(4, 1), written_at=torch.tensor(idx),
                     live=torch.ones(4, dtype=torch.bool), step=5)  # fmt: skip
    k = pol.select_eviction(st, torch.zeros(1), 5)
    low = min(means[kinds[i]] for i in idx)
    assert means[kinds[k]] == low


# --------------------------------------------------------------------------- #
# §7: random (A1 R5), fact/filler, oracle, one document per policy
# --------------------------------------------------------------------------- #


def test_the_random_arm_is_randompolicy_seeded_from_sha256(b2):
    pol = b2.random_policy(3, 1, 940007)
    assert isinstance(pol, RandomPolicy)
    h = hashlib.sha256(b"b2rand:3:1:940007").digest()[:8]
    assert b2.random_seed_int(3, 1, 940007) == int.from_bytes(h, "big")
    g = torch.Generator().manual_seed(int.from_bytes(h, "big"))
    assert torch.equal(pol.generator.get_state(), g.get_state())
    assert b2.random_seed_int(0, 1, 940007) != b2.random_seed_int(1, 1, 940007)


def test_the_random_arm_draws_over_all_live_slots_newest_included(b2):
    pol = b2.random_policy(0, 0, 940000)
    st = MemoryState(gestalts=torch.zeros(4, 1), written_at=torch.arange(4),
                     live=torch.ones(4, dtype=torch.bool), step=9)  # fmt: skip
    seen = {pol.select_eviction(st, torch.zeros(1), 9) for _ in range(200)}
    assert seen == {0, 1, 2, 3}


def test_fact_filler_is_w6s_rule_with_its_seed(b2):
    doc = _tiny_docs([940000])[0]
    pol = b2.factfiller_policy(doc, 2)
    assert pol.rng.random() == random.Random(f"ff:2:{doc.doc_id}").random()


def test_the_oracle_wrapper_refuses_another_documents_demand(b2):
    d0, d1 = _tiny_docs([940000, 940001])
    b2.CheckedOracle(d0, 0.9, discounted_demand(d0, 0.9))
    with pytest.raises(AssertionError):
        b2.CheckedOracle(d0, 0.9, discounted_demand(d1, 0.9))
    with pytest.raises(AssertionError):
        b2.CheckedOracle(d0, 0.9, discounted_demand(d0, 0.0))


def test_one_document_one_policy_and_residency_equals_the_replay(b2, tiny):
    d0, d1 = tiny["eval"]
    kw = {"vmap": tiny["vmap"], "S": TS, "m": TM, "L": TL}
    with pytest.raises(AssertionError, match="document"):
        b2.run_arm(tiny["model"], d0, b2.random_policy(0, 0, d1.doc_id), **kw)
    r = b2.run_arm(tiny["model"], d0, b2.random_policy(0, 0, d0.doc_id), **kw)
    assert r["residency_ok"] is True and r["sum_worst"] <= b2.SUM_TOL
    assert len(r["log"]) == TS - TM  # one eviction per full-memory step
    rep = simulate(d0, b2.Scripted(r["victims"]), TM)["queries"]
    assert [(q["gap"], q["hit"]) for q in rep] == r["hits"]


# --------------------------------------------------------------------------- #
# §9: bootstrap, ref, delta, power, the ceiling
# --------------------------------------------------------------------------- #


def test_the_bootstrap_is_paired_and_the_random_floor_is_the_five_seed_mean(b2):
    D = 50
    g = torch.Generator().manual_seed(0)
    n = torch.randint(1, 5, (D,), generator=g)
    per = {"a": torch.stack([n, n], 1)}  # always correct
    for k in range(5):
        per[f"random{k}"] = torch.stack([n, (n * 0 + (k % 2)).clamp(max=n)], 1)
    out = b2.paired_bootstrap(per, {"a_minus_rand": ("a", "random")}, seed=0, n_boot=50)
    rand_acc = sum(float(per[f"random{k}"][:, 1].sum() / n.sum()) for k in range(5)) / 5
    assert out["a_minus_rand"]["point"] == pytest.approx(1.0 - rand_acc)
    assert "sd" in out["a_minus_rand"]
    # the generator is seeded 20260927 + seed
    assert b2.BOOT_SEED_BASE == 20260927


def test_ref_is_the_better_of_fifo_and_age_on_fit_val_ties_to_fifo(b2):
    ids = [936000, 936001]
    assert b2.select_ref({"fifo": 0.70, "age": 0.72}, ids) == "age"
    assert b2.select_ref({"fifo": 0.72, "age": 0.72}, ids) == "fifo"
    assert b2.select_ref({"fifo": 0.73, "age": 0.72}, ids) == "fifo"


def test_ref_is_never_chosen_on_eval(b2):
    with pytest.raises(b2.RangeError):
        b2.select_ref({"fifo": 0.70, "age": 0.72}, [940000, 940001])


def test_delta_and_its_gamma_zero_rule(b2):
    assert b2.delta_of(0.94, 0.80) == pytest.approx(0.035)
    d = b2.deltas_by_gamma({0.9: 0.035, 0.0: 0.001})
    assert d == {0.9: 0.035, 0.0: 0.035}  # A1.11


def test_power_takes_the_max_over_gating_contrasts_only_and_clips(b2):
    assert b2.required_n(0.01, 0.04, 1024) == math.ceil(1024 * (1.96 * 0.01 / 0.02) ** 2)
    sig = {(c, s): 0.004 for c in b2.GATING_CONTRASTS for s in (0, 1, 2)}
    sig[("psiU_minus_kind", 0)] = 1.0  # Q2 does not enter the max (A1.12)
    out = b2.n_eval(sig, {0: 0.035, 1: 0.035, 2: 0.035}, 1024)
    assert out["N_E"] == 1024 and not out["underpowered"]  # clipped up
    sig[(b2.GATING_CONTRASTS[0], 1)] = 0.05
    out = b2.n_eval(sig, {0: 0.035, 1: 0.035, 2: 0.035}, 1024)
    assert out["N_E"] == 40000 and out["underpowered"]
    assert len(b2.GATING_CONTRASTS) == 6


def test_an_undefined_delta_makes_the_power_cap_bind(b2):
    sig = {(c, s): 0.004 for c in b2.GATING_CONTRASTS for s in (0, 1, 2)}
    out = b2.n_eval(sig, {0: 0.035, 1: -0.01, 2: 0.035}, 1024)
    assert out["N_E"] == 40000 and out["underpowered"]


def test_the_compute_ceiling_reduces_n_e_to_what_fits_in_72h(b2):
    ok = b2.compute_ceiling(40000, sec_per_arm_doc=0.01, arms=12, seeds=3, parallel=1)
    assert ok["N_E"] == 40000 and not ok["reduced"]
    cut = b2.compute_ceiling(40000, sec_per_arm_doc=1.0, arms=12, seeds=3, parallel=3)
    assert cut["N_E"] == math.floor(72 * 3600 * 3 / (1.0 * 12 * 3)) and cut["reduced"]
    assert cut["projected_h"] <= 72.0


# --------------------------------------------------------------------------- #
# §9.5-9.7 / A1.13: outcomes, the truth table, Q2
# --------------------------------------------------------------------------- #


def test_the_outcome_rule(b2):
    o = b2.outcome
    d = 0.04
    assert o(0.06, 0.01, 0.1, d, noninf_lo=-0.01, rand_lo=0.01) == "WIN"
    assert o(0.06, 0.01, 0.1, d, noninf_lo=-0.05, rand_lo=0.01) == "UNRESOLVED"
    assert o(0.06, 0.01, 0.1, d, noninf_lo=-0.01, rand_lo=-0.01) == "UNRESOLVED"
    assert o(0.03, 0.01, 0.05, d, noninf_lo=0.0, rand_lo=0.1) == "UNRESOLVED"
    assert o(0.0, -0.02, 0.02, d, noninf_lo=0.0, rand_lo=0.1) == "EQUIV"
    assert o(-0.1, -0.15, -0.05, d, noninf_lo=-1, rand_lo=-1) == "LOSS"
    assert o(-0.03, -0.05, -0.01, d, noninf_lo=-1, rand_lo=-1) == "UNRESOLVED"
    assert o(0.06, 0.01, 0.1, None, noninf_lo=0, rand_lo=1) == "UNRESOLVED"
    assert o(0.06, 0.01, 0.1, -0.01, noninf_lo=0, rand_lo=1) == "UNRESOLVED"


def test_a_ci_excluding_the_estimate_is_unresolved(b2):
    """A1.13: removes the only WIN and EQUIV overlap (Δ̂ ≥ δ > hi)."""
    assert b2.outcome(0.05, 0.001, 0.03, 0.04, noninf_lo=0, rand_lo=1) == "UNRESOLVED"
    assert b2.outcome_flags(0.05, 0.001, 0.03) == ["CI_EXCLUDES_ESTIMATE"]


def test_the_random_floor_is_part_of_win(b2):
    assert b2.outcome(0.06, 0.01, 0.1, 0.04, noninf_lo=0.0, rand_lo=0.0) != "WIN"


def test_the_truth_table_precedence(b2):
    W, E, L, U = "WIN", "EQUIV", "LOSS", "UNRESOLVED"
    c = b2.classify
    assert c([W, W, W], [W, W, L])[1] == "HARMFUL"
    assert c([L, W, W], [W, W, W])[1] == "HARMFUL"
    assert c([W, W, W], [W, W, W])[1] == "NOT RULED OUT, CENSORED"
    assert c([W, W, W], [W, E, W])[1] == "NOT RULED OUT, UNCENSORED ONLY"
    assert c([W, U, W], [W, W, W])[1] == "ANOMALY (C > U)"
    assert c([E, E, E], [E, E, E])[1] == "NOT LEARNABLE, offline"
    assert c([E, E, U], [E, E, E])[1] == "MIXED / UNRESOLVED"
    assert [c([W, W, W], [W, W, W])[0], c([E] * 3, [E] * 3)[0]] == [2, 5]


def test_q2_outcomes(b2):
    q = b2.q2_outcome
    assert q(0.05, 0.01, 0.09, 0.04) == "Q2-WIN"
    assert q(0.0, -0.02, 0.02, 0.04) == "Q2-EQUIV"
    assert q(-0.1, -0.2, -0.05, 0.04) == "Q2-LOSS"
    assert q(0.02, 0.01, 0.05, 0.04) == "Q2-UNRESOLVED"
    assert q(0.05, 0.001, 0.03, 0.04) == "Q2-UNRESOLVED"  # CI excludes estimate


# --------------------------------------------------------------------------- #
# §10 / A1.3 / A1.5: E0h
# --------------------------------------------------------------------------- #


def _one_step(tiny):
    model = tiny["model"]
    doc = tiny["eval"][0]
    ids, mask = encode([doc], tiny["vmap"], max_tokens=TL, steps=TS)
    return model, ids, mask


def test_the_logit_prehook_does_not_change_the_forward(b2, tiny):
    model, ids, mask = _one_step(tiny)
    lens = torch.full((1,), TS)
    outs_a, outs_b = [], []

    def sf(sink):
        def f(t, out, ids_t, mask_t, row_valid):
            sink.append((out.logits.clone(), out.srep.clone()))
            return torch.zeros(())

        return f

    with torch.no_grad():
        run_policy_loop(model, ids, mask, lens, FIFOPolicy(), step_fn=sf(outs_a))
        hook = b2.LogitHook(model)
        try:
            run_policy_loop(
                model, ids, mask, lens, FIFOPolicy(), step_fn=sf(outs_b), capture=True
            )
        finally:
            hook.remove()
    for (la, sa), (lb, sb) in zip(outs_a, outs_b, strict=True):
        assert torch.equal(la, lb) and torch.equal(sa, sb)
    assert len(hook.calls) == TS * len(model.cfg.cross_attention_layers)


def test_recomputed_logits_softmax_to_the_captured_alpha(b2, tiny):
    model, ids, mask = _one_step(tiny)
    lens = torch.full((1,), TS)
    worst = []

    with torch.no_grad():
        hook = b2.LogitHook(model)

        def f(t, out, ids_t, mask_t, row_valid):
            lg = hook.take()
            worst.append(b2.logit_control(lg, out.cross_attention, mask_t))
            return torch.zeros(())

        try:
            run_policy_loop(model, ids, mask, lens, FIFOPolicy(), step_fn=f, capture=True)
        finally:
            hook.remove()
    assert max(worst[1:]) <= b2.LOGIT_TOL  # step 0 has an empty memory


def test_logits_collapse_by_the_mean_over_real_query_tokens(b2):
    lg = torch.arange(2 * 1 * 3 * 2, dtype=torch.float32).reshape(1, 2, 3, 2)
    mask = torch.tensor([[1, 1, 0]])
    out = b2.collapse_mean(lg, mask)
    assert out.shape == (1, 2, 2)
    assert torch.allclose(out[0, 0], (lg[0, 0, 0] + lg[0, 0, 1]) / 2)


def test_within_step_r2_ignores_a_per_step_offset(b2):
    g = torch.Generator().manual_seed(0)
    X = torch.randn(60, 3, generator=g, dtype=torch.float64)
    groups = torch.arange(60) // 6
    y = X @ torch.tensor([1.0, -2.0, 0.5], dtype=torch.float64) + groups.double() * 7
    assert b2.within_step_r2(y, X, groups) == pytest.approx(1.0)
    assert b2.pooled_r2(y, X) < 1.0
    noise = torch.randn(60, generator=g, dtype=torch.float64)
    assert b2.within_step_r2(noise, X, groups) < 0.5


def test_e0h_classes_as_amended(b2):
    k = b2.e0h_classify
    assert k({0: 0.95, 1: 0.91, 2: 0.10}) == "COLLINEAR"
    assert k({0: 0.40, 1: 0.30, 2: 0.48}) == "NOT_COLLINEAR"
    assert k({0: 0.40, 1: None, 2: 0.48}) == "NOT_COLLINEAR"  # 2 informative
    assert k({0: 0.40, 1: None, 2: None}) == "INTERMEDIATE"  # 1 informative
    assert k({0: 0.40, 1: 0.60, 2: 0.48}) == "INTERMEDIATE"


def test_e0h_rc_is_its_own_and_is_2_until_ratified(b2):
    rc = b2.e0h_rc
    for cls in ("COLLINEAR", "NOT_COLLINEAR", "INTERMEDIATE"):
        assert rc(cls, ratified=False) == 2
    assert rc("COLLINEAR", ratified=True) == 1
    assert rc("NOT_COLLINEAR", ratified=True) == 0
    assert rc("INTERMEDIATE", ratified=True) == 2
    assert rc("DID_NOT_RUN", ratified=True) == 3


def test_e0h_without_its_fits_or_on_an_exception_exits_3(b2, tmp_path):
    assert b2.e0h_main(["--fits", str(tmp_path / "absent")]) == 3
    bad = tmp_path / "fits"
    bad.mkdir()
    (bad / "e0h_inputs.json").write_text("{not json")
    assert b2.e0h_main(["--fits", str(bad)]) == 3


def test_no_e0h_ruling_exists_so_e0h_is_unratified(b2):
    assert b2.e0h_ratified() is False


# --------------------------------------------------------------------------- #
# the EVAL guard and the claims writer
# --------------------------------------------------------------------------- #


def test_eval_refuses_while_n_e_is_not_in_the_prereg(b2):
    assert b2.main(["eval"]) == 3


def test_the_claims_writer_requires_claim_command_expected(b2, tmp_path):
    p = tmp_path / "claims.json"
    b2.write_claims(p, [{"claim": "c", "command": "echo 1", "expected": "1"}])
    assert json.loads(p.read_text())[0]["command"] == "echo 1"
    with pytest.raises(ValueError):
        b2.write_claims(p, [{"claim": "c", "command": "echo 1"}])
