"""experiments/b2-psi-probe/run.py (PLAN-v4 B2, with E0h): the pure pieces on
hand-built inputs, and the model side on a tiny untrained model. No checkpoint and
no document of FIT_TRAIN / FIT_VAL / EVAL at S = 48 is generated or read here; the
tiny fixtures generate a handful of S = 12 documents **by id** only where a range
guard needs an id inside a range, and never run a fit or an arm on the real model.

Governing text: experiments/b2-psi-probe/PREREG.md -- the base (e5ab398),
Amendment 1 (2ec60dd, which wins), the B0 addendum (99a6626).
"""

from __future__ import annotations

import ast
import hashlib
import importlib.util
import inspect
import json
import math
import random
import sys
from pathlib import Path

import pytest
import torch

from rsr.baselines.fifo import FIFOPolicy
from rsr.baselines.random_policy import RandomPolicy
from rsr.data.synthetic import (
    SyntheticConfig,
    _generate_document,
    discounted_demand,
    generate,
)
from rsr.metrics.headroom import simulate
from rsr.model.tg import TGConfig, TGModel
from rsr.model.tg.policy_loop import run_policy_loop
from rsr.retention.policy import MemoryState
from rsr.train.loop import build_vocab, encode

ROOT = Path(__file__).resolve().parents[1]
RUN = ROOT / "experiments" / "b2-psi-probe" / "run.py"
NAN = float("nan")


@pytest.fixture(scope="module")
def b2():
    spec = importlib.util.spec_from_file_location("b2_psi_probe_run", RUN)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["b2_psi_probe_run"] = mod
    spec.loader.exec_module(mod)
    return mod


# --------------------------------------------------------------------------- #
# tiny fixtures: S = 12, M = 4, D = 8 (p = 80), documents generated by id
# --------------------------------------------------------------------------- #

TS, TM, TL, TD = 12, 4, 16, 8


def _tiny_cfg(seed: int = 0) -> SyntheticConfig:
    return SyntheticConfig(
        sentences_per_document=TS, max_gap=8, heavy_tail_min=5, seed=seed
    )


def _tiny_docs(ids):
    return [_generate_document(i, _tiny_cfg()) for i in ids]


@pytest.fixture(scope="module")
def tiny():
    """A tiny untrained model and documents with ids inside B2's ranges."""
    train = _tiny_docs(range(920000, 920004))
    val = _tiny_docs(range(936000, 936003))
    ev = _tiny_docs(range(940000, 940002))
    vmap = build_vocab(train + val + ev)
    torch.manual_seed(0)
    cfg = TGConfig(
        D=TD,
        V=4 + len(vmap),
        F=22,
        max_sentence_tokens=TL,
        max_sentences_in_short_term=TM,
        pad_id=0,
        bos_id=1,
        eos_id=2,
        eod_id=3,
    )
    model = TGModel(cfg).eval()
    return {"model": model, "vmap": vmap, "train": train, "val": val, "eval": ev}


@pytest.fixture(scope="module")
def caps(b2, tiny):
    kw = {"vmap": tiny["vmap"], "S": TS, "m": TM, "L": TL}
    return {
        "train": [b2.capture_doc(tiny["model"], d, **kw) for d in tiny["train"]],
        "val": [b2.capture_doc(tiny["model"], d, **kw) for d in tiny["val"]],
        "eval": [b2.capture_doc(tiny["model"], d, **kw) for d in tiny["eval"]],
    }


def _state(gestalts, written_at, step):
    n = gestalts.shape[0]
    return MemoryState(
        gestalts=gestalts,
        written_at=torch.as_tensor(written_at, dtype=torch.long),
        live=torch.ones(n, dtype=torch.bool),
        step=step,
    )


# --------------------------------------------------------------------------- #
# §3 / A1.15: ranges, disjointness, aliasing, the guard
# --------------------------------------------------------------------------- #


def test_the_ranges_are_the_preregs(b2):
    assert b2.RANGES == {
        "FIT_TRAIN": (920000, 936000),
        "FIT_VAL": (936000, 937024),
        "EVAL": (940000, 980000),
    }
    assert b2.E0D_RESERVED == (900000, 920000)
    assert b2.USED_RANGES["E0d_A1"] == (262144, 263168)


def test_the_ranges_are_mutually_disjoint_and_clear_every_used_range(b2):
    assert b2.range_problems() == []


def test_an_overlap_with_any_used_range_is_a_problem(b2):
    used = {**b2.USED_RANGES, "planted": (936500, 936600)}
    probs = b2.range_problems(used=used)
    assert any("planted" in p and "FIT_VAL" in p for p in probs), probs
    probs = b2.range_problems(used={**b2.USED_RANGES, "e0d_like": (262144, 263168)})
    assert probs == []  # E0d's own range does not overlap B2's
    ranges = {**b2.RANGES, "EVAL": (262000, 263000)}
    assert any("E0d_A1" in p for p in b2.range_problems(ranges=ranges))


def test_b2_ranges_overlapping_each_other_or_e0ds_reservation_is_a_problem(b2):
    ranges = {**b2.RANGES, "FIT_VAL": (935000, 937024)}
    assert any("FIT_TRAIN" in p and "FIT_VAL" in p for p in b2.range_problems(ranges))
    ranges = {**b2.RANGES, "FIT_TRAIN": (910000, 936000)}
    assert any("E0D_RESERVED" in p for p in b2.range_problems(ranges))


def test_generator_seeds_do_not_alias_across_seeds(b2):
    assert b2.aliasing_problems() == []
    # an id past 1_000_003 aliases the next seed's low ids
    ranges = {**b2.RANGES, "EVAL": (1_000_000, 1_000_010)}
    assert b2.aliasing_problems(ranges=ranges) != []


def test_the_range_guard_refuses_an_id_outside_its_range(b2):
    b2.require_range([936000, 937023], "FIT_VAL")
    with pytest.raises(b2.RangeError):
        b2.require_range([936000, 940000], "FIT_VAL")
    with pytest.raises(b2.RangeError):
        b2.require_range([], "FIT_VAL")


def test_documents_by_id_are_the_generators_documents(b2):
    docs = generate(SyntheticConfig(sentences_per_document=48, seed=1, n_documents=3))
    for d in docs:
        assert b2.doc_by_id(1, d.doc_id) == d


def test_vocabulary_closure_reports_a_missing_word(b2, tiny):
    ok = b2.vocabulary_closure(tiny["train"], tiny["vmap"])
    assert ok["ok"] and ok["n_missing"] == 0
    vmap = dict(tiny["vmap"])
    vmap.pop(sorted(vmap)[0])
    assert not b2.vocabulary_closure(tiny["train"], vmap)["ok"]


# --------------------------------------------------------------------------- #
# §6: p, N_F, row counts
# --------------------------------------------------------------------------- #


def test_p_and_n_f_follow_the_amended_rule(b2):
    assert b2.p_of(128) == 16640
    assert b2.n_f(16640) == 264  # A1.15: ceil(10 p / 632)
    assert b2.u_rows(48) == 1128
    assert b2.c_rows(48, 16) == 632
    assert b2.N_E is None  # TBD-3: written by diff only before EVAL


# --------------------------------------------------------------------------- #
# §4: the feature maps and ProbeArgminPolicy
# --------------------------------------------------------------------------- #


def test_bilinear_features_are_vec_s_c_then_s_then_c(b2):
    s = torch.tensor([[1.0, 2.0]])
    c = torch.tensor([[3.0, 5.0]])
    f = b2.bilinear_features(s, c)
    assert f.dtype == torch.float64
    assert f.tolist() == [[3.0, 5.0, 6.0, 10.0, 1.0, 2.0, 3.0, 5.0]]
    w = torch.randn(8, dtype=torch.float64)
    W = w[:4].reshape(2, 2)
    manual = s.double() @ W @ c.double().T + w[4:6] @ s.double().T + w[6:] @ c.double().T
    assert torch.allclose(f @ w, manual.flatten())


def test_the_feature_builder_takes_s_and_c_and_nothing_else(b2):
    assert list(inspect.signature(b2.bilinear_features).parameters) == ["s_i", "c_t"]


def test_age_features_are_one_hot_on_one_to_s_minus_one(b2):
    f = b2.age_features(torch.tensor([1, 3, 11]), 12)
    assert f.shape == (3, 11) and f.dtype == torch.float64
    assert f.argmax(1).tolist() == [0, 2, 10] and f.sum().item() == 3.0
    with pytest.raises(ValueError):
        b2.age_features(torch.tensor([0]), 12)


def test_no_age_in_psi_hat_permuting_written_at_and_step_changes_nothing(b2):
    """§11 control 9: with the gestalts held fixed, ψ̂ does not move when
    written_at and the step are permuted."""
    torch.manual_seed(1)
    d = 3
    g = torch.randn(5, d)
    c = torch.randn(d)
    w = torch.randn(b2.p_of(d), dtype=torch.float64)
    doc = _tiny_docs([940000])[0]
    pol = b2.ProbeArgminPolicy(w, "bilinear", doc=doc, model_seed=0, arm="U", S=TS)
    a = pol.scores(_state(g, [2, 3, 4, 5, 6], 7), c, 7)
    b = pol.scores(_state(g, [6, 2, 5, 3, 4], 11), c, 11)
    assert torch.equal(a, b)
    assert b2.no_age_check(pol, g, c) is True


def test_the_probe_evicts_the_argmin_ties_to_the_oldest_and_logs_it(b2):
    doc = _tiny_docs([940000])[0]
    d = 2
    # w picks psi = u_s . s with u_s = (1, 0): scores are the first coordinate
    w = torch.zeros(b2.p_of(d), dtype=torch.float64)
    w[d * d] = 1.0
    pol = b2.ProbeArgminPolicy(w, "bilinear", doc=doc, model_seed=2, arm="U", S=TS)
    g = torch.tensor([[0.5, 0.0], [0.1, 9.0], [0.1, -9.0], [0.7, 0.0]])
    st = _state(g, [3, 4, 5, 6], 7)
    k = pol.select_eviction(st, torch.zeros(d), 7)
    assert k == 1  # 0.1 twice: the lower slot index
    rec = pol.log[-1]
    assert rec["victim_slot"] == 1 and rec["written_at"] == 4 and rec["age"] == 3
    assert rec["rank"] == 2 and rec["rank_shift"] == [2, 1]
    assert rec["margin"] == pytest.approx(0.0)
    assert rec["psi"] == pytest.approx([0.5, 0.1, 0.1, 0.7])
    assert rec["doc"] == doc.doc_id and rec["seed"] == 2 and rec["arm"] == "U"
    assert rec["kind"] in ("assert", "query", "filler")


def test_the_age_arm_reads_age_and_nothing_else(b2):
    doc = _tiny_docs([940000])[0]
    w = torch.zeros(TS - 1, dtype=torch.float64)
    w[2] = -1.0  # age 3 scores lowest
    pol = b2.ProbeArgminPolicy(w, "age", doc=doc, model_seed=0, arm="age_U", S=TS)
    st = _state(torch.zeros(4, 2), [3, 4, 5, 6], 7)
    assert pol.select_eviction(st, torch.zeros(2), 7) == 1  # written 4 -> age 3


def test_the_probe_policy_is_not_rsrpolicy_and_nothing_is_recorded(b2):
    src = RUN.read_text()
    tree = ast.parse(src)
    mods = {
        n.module for n in ast.walk(tree) if isinstance(n, ast.ImportFrom) and n.module
    }
    assert "rsr.retention.rsr" not in mods
    names = {n.id for n in ast.walk(tree) if isinstance(n, ast.Name)} | {
        a.name for n in ast.walk(tree) if isinstance(n, ast.ImportFrom) for a in n.names
    }
    assert "RSRPolicy" not in names and "RSRConfig" not in names
    calls = {
        n.func.attr
        for n in ast.walk(tree)
        if isinstance(n, ast.Call) and isinstance(n.func, ast.Attribute)
    }
    assert "record" not in calls and "from_registry" not in calls
    assert not hasattr(b2.ProbeArgminPolicy, "b") and not hasattr(b2, "nu")


# --------------------------------------------------------------------------- #
# §5: capture, stop-grad, probes, targets
# --------------------------------------------------------------------------- #


def test_stopgrad_cuts_the_graph(b2):
    x = torch.randn(3, requires_grad=True)
    y = b2._stopgrad(x * 2)
    assert not y.requires_grad and y.grad_fn is None


def test_captured_s_and_c_are_stop_grad_and_nothing_reaches_the_model(b2, tiny):
    model = tiny["model"]
    with torch.enable_grad():
        cap = b2.capture_doc(model, tiny["train"][0], vmap=tiny["vmap"], S=TS, m=TM, L=TL)
    for t in (cap.gest, cap.ctx):
        assert not t.requires_grad and t.grad_fn is None
    assert all(p.grad is None for p in model.parameters())
    # s_i is the gestalt the FIFO rollout wrote for sentence i, which is step i's srep
    assert torch.equal(cap.gest, cap.ctx)


def test_the_capture_fills_every_row_and_every_control_holds(b2, caps):
    for cap in caps["train"]:
        for r in b2.RANKS:
            D = cap.D[r]
            for t in range(1, TS):
                assert not torch.isnan(D[t, :t]).any(), (r, t)
            assert cap.identity_worst[r] <= b2.IDENTITY_TOL
        assert cap.sum_worst <= b2.SUM_TOL
        # resident sentences are FIFO's own r at every rank
        for r in (1, 2, 3):
            res = cap.resident
            assert torch.equal(cap.D[r][res], cap.D[0][res])


def test_row_counts_are_u_and_c(b2, caps):
    cap = caps["train"][0]
    t, i = b2.row_index(cap, "U", TM)
    assert len(t) == b2.u_rows(TS) and bool((i < t).all())
    t, i = b2.row_index(cap, "C", TM)
    assert len(t) == b2.c_rows(TS, TM)
    assert bool(cap.resident[t, i].all())


def test_probes_never_feed_back_into_the_fifo_rollout(b2, tiny, caps):
    """The capture's own FIFO answers equal a plain FIFO rollout's."""
    doc = tiny["train"][0]
    plain = b2.run_arm(
        tiny["model"],
        doc,
        b2.Logged(FIFOPolicy(), doc=doc, model_seed=0, arm="fifo"),
        vmap=tiny["vmap"],
        S=TS,
        m=TM,
        L=TL,
    )
    assert caps["train"][0].answers == plain["answers"]


def test_a_rank_r_probe_reads_the_swapped_in_sentence_at_rank_r(b2, tiny, caps):
    """One evicted sentence at one step, recomputed by hand at rank 2."""
    cap = caps["train"][1]
    t, i, r = TS - 1, 0, 2
    val = b2.probe_by_hand(
        tiny["model"], tiny["train"][1], cap, t, i, r, vmap=tiny["vmap"], m=TM, L=TL
    )
    assert cap.D[r][t, i].item() == pytest.approx(val, abs=1e-6)


def test_returns_start_at_k0_and_the_shifted_companion_starts_at_k1(b2):
    X = torch.tensor(
        [[NAN, NAN, NAN], [1.0, NAN, NAN], [2.0, 4.0, NAN]], dtype=torch.float64
    )
    G = b2.returns(X, 0.5)
    assert G[1, 0] == pytest.approx(1 + 0.5 * 2) and G[2, 1] == pytest.approx(4.0)
    Gp = b2.shifted(G)
    assert Gp[1, 0] == pytest.approx(2.0)  # sum_{k>=1} g^{k-1} X[t+k]
    assert Gp[2, 0] == 0.0 and Gp[2, 1] == 0.0  # t = S-1: empty sum
    assert math.isnan(Gp[0, 0])
    G0 = b2.returns(X, 0.0)
    assert torch.equal(b2.shifted(G0)[1, :1], X[2, :1])  # gamma 0: X[t+1]


def test_the_censored_target_is_zero_after_fifo_evicts(b2, caps):
    cap = caps["train"][0]
    lit = b2.literal(cap.D[0], cap.resident)
    t = TS - 1
    assert lit[t, 0] == 0.0 and not bool(cap.resident[t, 0])
    assert lit[t, t - 1] == cap.D[0][t, t - 1]


def test_target_matrices_by_arm(b2, caps):
    cap = caps["train"][0]
    U = b2.target_matrix(cap, "U", 0.9)
    assert torch.allclose(U, b2.returns(cap.D[0], 0.9), equal_nan=True)
    U2 = b2.target_matrix(cap, "U2", 0.9)
    assert torch.allclose(U2, b2.returns(cap.D[2], 0.9), equal_nan=True)
    Cp = b2.target_matrix(cap, "C+", 0.0)
    lit = b2.literal(cap.D[0], cap.resident)
    assert torch.allclose(
        Cp[1:-1],
        torch.nan_to_num(lit[2:], nan=0.0).where(
            ~torch.isnan(lit[1:-1]), torch.tensor(NAN, dtype=torch.float64)
        ),
        equal_nan=True,
    )
    A = b2.target_matrix(cap, "age", None)
    assert A[5, 2] == 3.0


# --------------------------------------------------------------------------- #
# §6 / A1.6 / A1.7: the ridge
# --------------------------------------------------------------------------- #


def _ridge_problem(n=200, p=6, seed=0):
    g = torch.Generator().manual_seed(seed)
    X = torch.randn(n, p, generator=g, dtype=torch.float64)
    y = X @ torch.randn(p, generator=g, dtype=torch.float64)
    return X, y


def test_the_spectral_ridge_solves_the_normal_equations(b2):
    X, y = _ridge_problem()
    G = b2.Gram(X.shape[1], 1)
    G.add(X[:100], y[:100, None])
    G.add(X[100:], y[100:, None])
    assert torch.allclose(G.xtx, X.T @ X) and G.n == 200
    path = b2.solve_path(G.xtx, G.xty[:, 0], b2.LAMBDAS)
    for pt in path:
        lam_eff = pt["lam"] * float(torch.trace(G.xtx)) / X.shape[1]
        assert pt["lam_eff"] == pytest.approx(lam_eff)
        ref = torch.linalg.solve(
            G.xtx + lam_eff * torch.eye(6, dtype=torch.float64), G.xty[:, 0]
        )
        assert torch.allclose(pt["w"], ref, atol=1e-8)
        assert pt["resid"] <= 1e-8 and pt["eligible"]


def test_the_gram_refuses_a_tensor_that_carries_graph(b2):
    G = b2.Gram(2, 1)
    with pytest.raises(ValueError, match="stop-grad"):
        G.add(
            torch.randn(3, 2, dtype=torch.float64, requires_grad=True),
            torch.zeros(3, 1, dtype=torch.float64),
        )


def test_lambda_selection_takes_the_min_ties_to_the_larger_and_only_eligible(b2):
    path = [
        {"lam": 1e-2, "resid": 1e-12, "eligible": True},
        {"lam": 1e-1, "resid": 1e-12, "eligible": True},
        {"lam": 1.0, "resid": 1e-12, "eligible": True},
    ]
    assert b2.select_lambda(path, [0.5, 0.2, 0.2]) == 2  # tie -> larger lambda
    path[0]["eligible"], path[0]["resid"] = False, 1e-5
    assert b2.select_lambda(path, [0.1, 0.2, 0.3]) == 1  # ineligible skipped


def test_a_selected_lambda_over_1e8_residual_or_no_eligible_point_exits_1(b2):
    path = [
        {"lam": 1e-2, "resid": 5e-8, "eligible": True},
        {"lam": 1.0, "resid": 1e-12, "eligible": True},
    ]
    with pytest.raises(b2.RidgeFailure, match="1e-08"):
        b2.select_lambda(path, [0.1, 0.2])
    for p in path:
        p["eligible"] = False
    with pytest.raises(b2.RidgeFailure, match="no eligible"):
        b2.select_lambda(path, [0.1, 0.2])
    assert b2.RidgeFailure.exit_code == 1


def test_within_step_demeaning_removes_a_per_step_offset(b2):
    v = torch.tensor([1.0, 3.0, 10.0, 14.0], dtype=torch.float64)
    g = torch.tensor([0, 0, 1, 1])
    assert b2.within_step_demean(v, g).tolist() == [-1.0, 1.0, -2.0, 2.0]


def test_lambda_is_chosen_on_fit_val_and_never_on_eval(b2, caps):
    """A1.7: the fit's lambda comes from FIT_VAL rows. Handing it EVAL's rows is
    a range error, not a quietly different lambda."""
    fit = b2.fit_heads(caps["train"], caps["val"], "C", "bilinear", [("C", 0.9)], m=TM)
    assert fit[("C", 0.9)]["val_range"] == "FIT_VAL"
    with pytest.raises(b2.RangeError):
        b2.fit_heads(caps["train"], caps["eval"], "C", "bilinear", [("C", 0.9)], m=TM)
    with pytest.raises(b2.RangeError):
        b2.fit_heads(caps["val"], caps["val"], "C", "bilinear", [("C", 0.9)], m=TM)


def test_the_fit_selects_on_demeaned_val_mse_and_reports_raw(b2, caps):
    fit = b2.fit_heads(
        caps["train"], caps["val"], "U", "bilinear", [("U", 0.9), ("U+", 0.0)], m=TM
    )
    for f in fit.values():
        k = f["selected"]
        dm = f["val_mse_demeaned"]
        assert dm[k] == min(
            x for x, p in zip(dm, f["path"], strict=True) if p["eligible"]
        )
        assert len(f["val_mse_raw"]) == len(b2.LAMBDAS)
        assert f["w"].dtype == torch.float64 and f["w"].shape == (b2.p_of(TD),)
        assert f["path"][k]["resid"] <= b2.SELECTED_RESID


def test_the_age_head_fits_one_hot_age_with_the_same_rule(b2, caps):
    fit = b2.fit_heads(caps["train"], caps["val"], "C", "age", [("C", 0.9)], m=TM)
    assert fit[("C", 0.9)]["w"].shape == (TS - 1,)


def test_age_decodability_is_raw_mse_lambda_and_r2_on_fit_val(b2, caps):
    out = b2.age_decodability(caps["train"], caps["val"], "U", m=TM)
    assert out["lambda_rule"] == "raw_val_mse" and out["val_range"] == "FIT_VAL"
    assert out["r2"] <= 1.0


def _independent_r2(b2, caps, rowset, feature, arm, gamma, w, *, full_memory_only):
    """R² = 1 - SSE/SST recomputed from scratch: FIT_VAL rows, the fitted `w`, the
    raw target and its own mean. Shares nothing with fit_heads's accumulators."""
    preds, ys = [], []
    for cap in caps:
        t, i = b2.row_index(cap, rowset, TM)
        if full_memory_only:
            keep = t >= TM
            t, i = t[keep], i[keep]
        preds.append(b2.design(cap, t, i, feature) @ w.to(torch.float64))
        ys.append(b2.target_matrix(cap, arm, gamma)[t, i])
    p, y = torch.cat(preds), torch.cat(ys)
    return 1.0 - float(((p - y) ** 2).sum()) / float(((y - y.mean()) ** 2).sum())


def test_val_r2_raw_is_one_minus_sse_over_sst(b2, caps):
    """§6 / §8.1: the logged FIT_VAL R² of the selected λ equals an independent
    1 - SSE/SST, for a demeaned-selection head (full-memory rows) and for the
    age-decodability predictor (all rows). The phase-A ledger logged
    1 - n_val·SSE/SST (an SSE already summed, multiplied by n again): values near
    -2e5 where 0.83 was right, and every E0h seed read UNINFORMATIVE (A1.3)."""
    fit = b2.fit_heads(caps["train"], caps["val"], "U", "bilinear", [("U", 0.0)], m=TM)[
        ("U", 0.0)
    ]
    got = fit["val_r2_raw"][fit["selected"]]
    want = _independent_r2(
        b2, caps["val"], "U", "bilinear", "U", 0.0, fit["w"], full_memory_only=True
    )
    assert got == pytest.approx(want, rel=1e-9, abs=1e-9)
    dec = b2.age_decodability(caps["train"], caps["val"], "U", m=TM)
    want_age = _independent_r2(
        b2, caps["val"], "U", "bilinear", "age", None, dec["w"], full_memory_only=False
    )
    assert dec["r2"] == pytest.approx(want_age, rel=1e-9, abs=1e-9)
    assert -1.0 < dec["r2"] <= 1.0  # the wrong form sits near -n_val here


def test_age_decodability_split_by_index_partitions_the_fit_val_rows(b2, caps):
    """Build review F11: the i < M / i ≥ M split covers every FIT_VAL row once, and
    is recomputed from the same w (a perfect predictor gives R² = 1 on both)."""
    out = b2.age_decodability(caps["train"], caps["val"], "U", m=TM)
    sp = out["r2_split"]
    assert sp["i_lt_M"]["n"] + sp["i_ge_M"]["n"] == out["n_val_rows"]
    assert sp["i_lt_M"]["n"] > 0 and sp["i_ge_M"]["n"] > 0
    assert out["resid"] <= b2.SELECTED_RESID
    with pytest.raises(b2.RangeError):
        b2.r2_split_by_index(caps["train"], "U", out["w"], m=TM)


# --------------------------------------------------------------------------- #
# §6 / A1.10: the kind-oracle
# --------------------------------------------------------------------------- #


def test_class_means_use_fit_train_u_rows_at_full_memory(b2, caps):
    m = b2.class_means(caps["train"], 0.9, m=TM)
    assert set(m) <= {"assert", "query", "filler"}
    # by hand
    vals: dict[str, list[float]] = {}
    for cap in caps["train"]:
        G = b2.target_matrix(cap, "U", 0.9)
        for t in range(TM, TS):
            for i in range(t):
                vals.setdefault(cap.kinds[i], []).append(float(G[t, i]))
    for k, v in vals.items():
        assert m[k] == pytest.approx(sum(v) / len(v))
    with pytest.raises(b2.RangeError):
        b2.class_means(caps["val"], 0.9, m=TM)


def test_kind_oracle_ties_are_uniform_random_seeded_per_step(b2):
    """A1.10: ties inside the lowest class are broken by
    random.Random(f"ko:{seed}:{doc_id}:{t}"), never by age."""
    doc = _tiny_docs([940001])[0]
    means = {"assert": 1.0, "query": 1.0, "filler": 1.0}  # everything ties
    picks = []
    for t in range(20, 60):
        pol = b2.KindOracle(means, doc=doc, model_seed=1, tie="random", S=TS)
        st = MemoryState(
            gestalts=torch.zeros(4, 1),
            written_at=torch.tensor([0, 1, 2, 3]),
            live=torch.ones(4, dtype=torch.bool),
            step=t,
        )
        k = pol.select_eviction(st, torch.zeros(1), t)
        rng = random.Random(f"ko:1:{doc.doc_id}:{t}")
        assert k == rng.choice([0, 1, 2, 3])
        picks.append(k)
    assert len(set(picks)) > 1  # not the oldest every time
    old = b2.KindOracle(means, doc=doc, model_seed=1, tie="oldest", S=TS)
    assert old.select_eviction(st, torch.zeros(1), 30) == 0


def test_kind_oracle_evicts_the_lowest_class(b2):
    doc = _tiny_docs([940001])[0]
    kinds = [s.kind for s in doc.sentences]
    means = {"assert": 3.0, "query": 2.0, "filler": 1.0}
    pol = b2.KindOracle(means, doc=doc, model_seed=0, tie="random", S=TS)
    idx = list(range(4))
    st = MemoryState(
        gestalts=torch.zeros(4, 1),
        written_at=torch.tensor(idx),
        live=torch.ones(4, dtype=torch.bool),
        step=5,
    )
    k = pol.select_eviction(st, torch.zeros(1), 5)
    low = min(means[kinds[i]] for i in idx)
    assert means[kinds[k]] == low


# --------------------------------------------------------------------------- #
# §7: random (A1 R5), fact/filler, oracle, one document per policy
# --------------------------------------------------------------------------- #


def test_the_random_arm_is_randompolicy_seeded_from_sha256(b2):
    pol = b2.random_policy(3, 1, 940007)
    assert isinstance(pol, RandomPolicy)
    h = hashlib.sha256(b"b2rand:3:1:940007").digest()[:8]
    assert b2.random_seed_int(3, 1, 940007) == int.from_bytes(h, "big")
    g = torch.Generator().manual_seed(int.from_bytes(h, "big"))
    assert torch.equal(pol.generator.get_state(), g.get_state())
    assert b2.random_seed_int(0, 1, 940007) != b2.random_seed_int(1, 1, 940007)


def test_the_random_arm_draws_over_all_live_slots_newest_included(b2):
    pol = b2.random_policy(0, 0, 940000)
    st = MemoryState(
        gestalts=torch.zeros(4, 1),
        written_at=torch.arange(4),
        live=torch.ones(4, dtype=torch.bool),
        step=9,
    )
    seen = {pol.select_eviction(st, torch.zeros(1), 9) for _ in range(200)}
    assert seen == {0, 1, 2, 3}


def test_fact_filler_is_w6s_rule_with_its_seed(b2):
    doc = _tiny_docs([940000])[0]
    pol = b2.factfiller_policy(doc, 2)
    assert pol.rng.random() == random.Random(f"ff:2:{doc.doc_id}").random()


def test_the_oracle_wrapper_refuses_another_documents_demand(b2):
    d0, d1 = _tiny_docs([940000, 940001])
    b2.CheckedOracle(d0, 0.9, discounted_demand(d0, 0.9))
    with pytest.raises(b2.ControlFailure):
        b2.CheckedOracle(d0, 0.9, discounted_demand(d1, 0.9))
    with pytest.raises(b2.ControlFailure):
        b2.CheckedOracle(d0, 0.9, discounted_demand(d0, 0.0))


def test_one_document_one_policy_and_residency_equals_the_replay(b2, tiny):
    d0, d1 = tiny["eval"]
    kw = {"vmap": tiny["vmap"], "S": TS, "m": TM, "L": TL}
    with pytest.raises(b2.ControlFailure, match="document"):
        b2.run_arm(tiny["model"], d0, b2.random_policy(0, 0, d1.doc_id), **kw)
    r = b2.run_arm(tiny["model"], d0, b2.random_policy(0, 0, d0.doc_id), **kw)
    assert r["residency_ok"] is True and r["sum_worst"] <= b2.SUM_TOL
    assert len(r["log"]) == TS - TM  # one eviction per full-memory step
    rep = simulate(d0, b2.Scripted(r["victims"]), TM)["queries"]
    assert [(q["gap"], q["hit"]) for q in rep] == r["hits"]


# --------------------------------------------------------------------------- #
# §9: bootstrap, ref, delta, power, the ceiling
# --------------------------------------------------------------------------- #


def test_the_bootstrap_is_paired_and_the_random_floor_is_the_five_seed_mean(b2):
    D = 50
    g = torch.Generator().manual_seed(0)
    n = torch.randint(1, 5, (D,), generator=g)
    per = {"a": torch.stack([n, n], 1)}  # always correct
    for k in range(5):
        per[f"random{k}"] = torch.stack([n, (n * 0 + (k % 2)).clamp(max=n)], 1)
    out = b2.paired_bootstrap(per, {"a_minus_rand": ("a", "random")}, seed=0, n_boot=50)
    rand_acc = sum(float(per[f"random{k}"][:, 1].sum() / n.sum()) for k in range(5)) / 5
    assert out["a_minus_rand"]["point"] == pytest.approx(1.0 - rand_acc)
    assert "sd" in out["a_minus_rand"]
    # the generator is seeded 20260927 + seed
    assert b2.BOOT_SEED_BASE == 20260927


def test_ref_is_the_better_of_fifo_and_age_on_fit_val_ties_to_fifo(b2):
    ids = [936000, 936001]
    assert b2.select_ref({"fifo": 0.70, "age": 0.72}, ids) == "age"
    assert b2.select_ref({"fifo": 0.72, "age": 0.72}, ids) == "fifo"
    assert b2.select_ref({"fifo": 0.73, "age": 0.72}, ids) == "fifo"


def test_ref_is_never_chosen_on_eval(b2):
    with pytest.raises(b2.RangeError):
        b2.select_ref({"fifo": 0.70, "age": 0.72}, [940000, 940001])


def test_delta_and_its_gamma_zero_rule(b2):
    assert b2.delta_of(0.94, 0.80) == pytest.approx(0.035)
    d = b2.deltas_by_gamma({0.9: 0.035, 0.0: 0.001})
    assert d == {0.9: 0.035, 0.0: 0.035}  # A1.11


def test_power_takes_the_max_over_gating_contrasts_only_and_clips(b2):
    assert b2.required_n(0.01, 0.04, 1024) == math.ceil(1024 * (1.96 * 0.01 / 0.02) ** 2)
    sig = {(c, s): 0.004 for c in b2.GATING_CONTRASTS for s in (0, 1, 2)}
    sig[("psiU_minus_kind", 0)] = 1.0  # Q2 does not enter the max (A1.12)
    out = b2.n_eval(sig, {0: 0.035, 1: 0.035, 2: 0.035}, 1024)
    assert out["N_E"] == 1024 and not out["underpowered"]  # clipped up
    sig[(b2.GATING_CONTRASTS[0], 1)] = 0.06  # N = 46,244 > 40,000
    out = b2.n_eval(sig, {0: 0.035, 1: 0.035, 2: 0.035}, 1024)
    assert out["N_E"] == 40000 and out["underpowered"]
    assert len(b2.GATING_CONTRASTS) == 6


def test_an_undefined_delta_makes_the_power_cap_bind(b2):
    sig = {(c, s): 0.004 for c in b2.GATING_CONTRASTS for s in (0, 1, 2)}
    out = b2.n_eval(sig, {0: 0.035, 1: -0.01, 2: 0.035}, 1024)
    assert out["N_E"] == 40000 and out["underpowered"]


def test_the_compute_ceiling_reduces_n_e_to_what_fits_in_72h(b2):
    ok = b2.compute_ceiling(40000, sec_per_arm_doc=0.01, arms=12, seeds=3, parallel=1)
    assert ok["N_E"] == 40000 and not ok["reduced"]
    cut = b2.compute_ceiling(40000, sec_per_arm_doc=1.0, arms=12, seeds=3, parallel=3)
    assert cut["N_E"] == math.floor(72 * 3600 * 3 / (1.0 * 12 * 3)) and cut["reduced"]
    assert cut["projected_h"] <= 72.0


# --------------------------------------------------------------------------- #
# §9.5-9.7 / A1.13: outcomes, the truth table, Q2
# --------------------------------------------------------------------------- #


def test_the_outcome_rule(b2):
    o = b2.outcome
    d = 0.04
    assert o(0.06, 0.01, 0.1, d, noninf_lo=-0.01, rand_lo=0.01) == "WIN"
    assert o(0.06, 0.01, 0.1, d, noninf_lo=-0.05, rand_lo=0.01) == "UNRESOLVED"
    assert o(0.06, 0.01, 0.1, d, noninf_lo=-0.01, rand_lo=-0.01) == "UNRESOLVED"
    assert o(0.03, 0.01, 0.05, d, noninf_lo=0.0, rand_lo=0.1) == "UNRESOLVED"
    assert o(0.0, -0.02, 0.02, d, noninf_lo=0.0, rand_lo=0.1) == "EQUIV"
    assert o(-0.1, -0.15, -0.05, d, noninf_lo=-1, rand_lo=-1) == "LOSS"
    assert o(-0.03, -0.05, -0.01, d, noninf_lo=-1, rand_lo=-1) == "UNRESOLVED"
    assert o(0.06, 0.01, 0.1, None, noninf_lo=0, rand_lo=1) == "UNRESOLVED"
    assert o(0.06, 0.01, 0.1, -0.01, noninf_lo=0, rand_lo=1) == "UNRESOLVED"


def test_a_ci_excluding_the_estimate_is_unresolved(b2):
    """A1.13: removes the only WIN and EQUIV overlap (Δ̂ ≥ δ > hi)."""
    assert b2.outcome(0.05, 0.001, 0.03, 0.04, noninf_lo=0, rand_lo=1) == "UNRESOLVED"
    assert b2.outcome_flags(0.05, 0.001, 0.03) == ["CI_EXCLUDES_ESTIMATE"]


def test_the_random_floor_is_part_of_win(b2):
    assert b2.outcome(0.06, 0.01, 0.1, 0.04, noninf_lo=0.0, rand_lo=0.0) != "WIN"


def test_the_truth_table_precedence(b2):
    W, E, L, U = "WIN", "EQUIV", "LOSS", "UNRESOLVED"
    c = b2.classify
    assert c([W, W, W], [W, W, L])[1] == "HARMFUL"
    assert c([L, W, W], [W, W, W])[1] == "HARMFUL"
    assert c([W, W, W], [W, W, W])[1] == "NOT RULED OUT, CENSORED"
    assert c([W, W, W], [W, E, W])[1] == "NOT RULED OUT, UNCENSORED ONLY"
    assert c([W, U, W], [W, W, W])[1] == "ANOMALY (C > U)"
    assert c([E, E, E], [E, E, E])[1] == "NOT LEARNABLE, offline"
    assert c([E, E, U], [E, E, E])[1] == "MIXED / UNRESOLVED"
    assert [c([W, W, W], [W, W, W])[0], c([E] * 3, [E] * 3)[0]] == [2, 5]


def test_q2_outcomes(b2):
    q = b2.q2_outcome
    assert q(0.05, 0.01, 0.09, 0.04) == "Q2-WIN"
    assert q(0.0, -0.02, 0.02, 0.04) == "Q2-EQUIV"
    assert q(-0.1, -0.2, -0.05, 0.04) == "Q2-LOSS"
    assert q(0.02, 0.01, 0.05, 0.04) == "Q2-UNRESOLVED"
    assert q(0.05, 0.001, 0.03, 0.04) == "Q2-UNRESOLVED"  # CI excludes estimate


# --------------------------------------------------------------------------- #
# §10 / A1.3 / A1.5: E0h
# --------------------------------------------------------------------------- #


def _one_step(tiny):
    model = tiny["model"]
    doc = tiny["eval"][0]
    ids, mask = encode([doc], tiny["vmap"], max_tokens=TL, steps=TS)
    return model, ids, mask


def test_the_logit_prehook_does_not_change_the_forward(b2, tiny):
    model, ids, mask = _one_step(tiny)
    lens = torch.full((1,), TS)
    outs_a, outs_b = [], []

    def sf(sink):
        def f(t, out, ids_t, mask_t, row_valid):
            sink.append((out.logits.clone(), out.srep.clone()))
            return torch.zeros(())

        return f

    with torch.no_grad():
        run_policy_loop(model, ids, mask, lens, FIFOPolicy(), step_fn=sf(outs_a))
        hook = b2.LogitHook(model)
        try:
            run_policy_loop(
                model, ids, mask, lens, FIFOPolicy(), step_fn=sf(outs_b), capture=True
            )
        finally:
            hook.remove()
    for (la, sa), (lb, sb) in zip(outs_a, outs_b, strict=True):
        assert torch.equal(la, lb) and torch.equal(sa, sb)
    assert len(hook.calls) == TS * len(model.cfg.cross_attention_layers)


def test_recomputed_logits_softmax_to_the_captured_alpha(b2, tiny):
    model, ids, mask = _one_step(tiny)
    lens = torch.full((1,), TS)
    worst = []

    with torch.no_grad():
        hook = b2.LogitHook(model)

        def f(t, out, ids_t, mask_t, row_valid):
            lg = hook.take()
            worst.append(b2.logit_control(lg, out.cross_attention, mask_t))
            return torch.zeros(())

        try:
            run_policy_loop(model, ids, mask, lens, FIFOPolicy(), step_fn=f, capture=True)
        finally:
            hook.remove()
    assert max(worst[1:]) <= b2.LOGIT_TOL  # step 0 has an empty memory


def test_logits_collapse_by_the_mean_over_real_query_tokens(b2):
    lg = torch.arange(2 * 1 * 3 * 2, dtype=torch.float32).reshape(1, 2, 3, 2)
    mask = torch.tensor([[1, 1, 0]])
    out = b2.collapse_mean(lg, mask)
    assert out.shape == (1, 2, 2)
    assert torch.allclose(out[0, 0], (lg[0, 0, 0] + lg[0, 0, 1]) / 2)


def test_within_step_r2_ignores_a_per_step_offset(b2):
    g = torch.Generator().manual_seed(0)
    X = torch.randn(60, 3, generator=g, dtype=torch.float64)
    groups = torch.arange(60) // 6
    y = X @ torch.tensor([1.0, -2.0, 0.5], dtype=torch.float64) + groups.double() * 7
    assert b2.within_step_r2(y, X, groups) == pytest.approx(1.0)
    assert b2.pooled_r2(y, X) < 1.0
    noise = torch.randn(60, generator=g, dtype=torch.float64)
    assert b2.within_step_r2(noise, X, groups) < 0.5


def test_e0h_classes_as_amended(b2):
    k = b2.e0h_classify
    assert k({0: 0.95, 1: 0.91, 2: 0.10}) == "COLLINEAR"
    assert k({0: 0.40, 1: 0.30, 2: 0.48}) == "NOT_COLLINEAR"
    assert k({0: 0.40, 1: None, 2: 0.48}) == "NOT_COLLINEAR"  # 2 informative
    assert k({0: 0.40, 1: None, 2: None}) == "INTERMEDIATE"  # 1 informative
    assert k({0: 0.40, 1: 0.60, 2: 0.48}) == "INTERMEDIATE"


def test_e0h_rc_is_its_own_and_is_2_until_ratified(b2):
    rc = b2.e0h_rc
    for cls in ("COLLINEAR", "NOT_COLLINEAR", "INTERMEDIATE"):
        assert rc(cls, ratified=False) == 2
    assert rc("COLLINEAR", ratified=True) == 1
    assert rc("NOT_COLLINEAR", ratified=True) == 0
    assert rc("INTERMEDIATE", ratified=True) == 2
    assert rc("DID_NOT_RUN", ratified=True) == 3


def test_e0h_without_its_fits_or_on_an_exception_exits_3(b2, tmp_path):
    fits, ev = tmp_path / "fits", tmp_path / "eval"
    args = ["--fits", str(fits), "--eval-dir", str(ev)]
    assert b2.e0h_main(args) == 3  # inputs absent
    fits.mkdir()
    ev.mkdir()
    for s in b2.SEEDS:  # present but unreadable: torch.load raises inside e0h
        (fits / f"ckpt3000-seed{s}.pt").write_text("not a checkpoint")
        (ev / f"ckpt3000-seed{s}.e0h.pt").write_text("not a checkpoint")
    assert b2.e0h_main(args) == 3
    assert "Traceback" in (ev / "e0h_traceback.txt").read_text()
    assert not (fits / "e0h_traceback.txt").exists()  # the phase-A record is read only


def test_e0h_reads_a_pre_fix_r2_only_through_its_erratum(b2, tmp_path):
    """Erratum P0.2: a phase-A payload logged 1 - n*SSE/SST and carries no
    ``val_r2_form``. E0h must not gate on that value raw; it reads the sidecar's
    corrected value, and with no sidecar it refuses (exit 3 via e0h_main)."""
    n, true_r2 = 1000, 0.66
    logged = 1.0 - n * (1.0 - true_r2)
    assert b2.r2_from_logged_n_val_form(logged, n) == pytest.approx(true_r2, abs=1e-12)
    legacy = {"val_r2_raw": [logged], "selected": 0, "n_val_rows": n}
    with pytest.raises(b2.ControlFailure):
        b2.selected_val_r2(legacy, tmp_path, 3000, 0, "U@0.0")
    side = b2.r2_sidecar_path(tmp_path, 3000, 0)
    row = {"original": logged, "corrected": b2.r2_from_logged_n_val_form(logged, n)}
    side.write_text(json.dumps({"heads": {"U@0.0": row}}))
    assert b2.selected_val_r2(legacy, tmp_path, 3000, 0, "U@0.0") == row["corrected"]
    stale = dict(legacy, val_r2_raw=[logged + 1.0])  # sidecar for another payload
    with pytest.raises(b2.ControlFailure):
        b2.selected_val_r2(stale, tmp_path, 3000, 0, "U@0.0")
    fixed = {"val_r2_raw": [0.5], "selected": 0, "val_r2_form": b2.R2_FORM}
    assert b2.selected_val_r2(fixed, tmp_path, 3000, 0, "U@0.0") == 0.5


def test_no_e0h_ruling_exists_so_e0h_is_unratified(b2):
    assert b2.e0h_ratified() is False


# --------------------------------------------------------------------------- #
# the EVAL guard and the claims writer
# --------------------------------------------------------------------------- #


def test_eval_refuses_while_n_e_is_not_in_the_prereg(b2, monkeypatch):
    monkeypatch.setattr(b2, "N_E", None)
    assert b2.main(["eval"]) == 3
    assert b2.main(["eval-child", "--checkpoint", "3000", "--seed", "0"]) == 3


def test_the_claims_writer_requires_claim_command_expected(b2, tmp_path):
    p = tmp_path / "claims.json"
    b2.write_claims(p, [{"claim": "c", "command": "echo 1", "expected": "1"}])
    assert json.loads(p.read_text())[0]["command"] == "echo 1"
    with pytest.raises(ValueError):
        b2.write_claims(p, [{"claim": "c", "command": "echo 1"}])


# --------------------------------------------------------------------------- #
# the phase cores end to end on the tiny model (A1.4 tiers, E0h streaming)
# --------------------------------------------------------------------------- #


def test_the_tiers_are_a1_4s_table(b2):
    p3 = b2.tier_plan(3000)
    assert len(p3[(0.9, "tier1")]) == 12
    assert len(p3[(0.9, "tier2")]) + len(p3[(0.0, "tier2")]) == 16
    p25 = b2.tier_plan(2500)
    assert sum(len(v) for v in p25.values()) == 28
    assert "fifo" in p3[(0.9, "tier1")] and "kind" in p3[(0.9, "tier1")]


def test_the_streamed_r2_equals_the_direct_r2(b2):
    g = torch.Generator().manual_seed(3)
    X = torch.randn(80, 4, generator=g, dtype=torch.float64)
    groups = torch.arange(80) // 8
    y = X @ torch.tensor([0.3, -1.0, 2.0, 0.0], dtype=torch.float64)
    y = y + torch.randn(80, generator=g, dtype=torch.float64) + groups.double()
    acc = b2.R2Acc(4)
    for k in range(10):  # one (document, t) group per call
        sl = slice(8 * k, 8 * k + 8)
        acc.add(y[sl], X[sl], groups[sl])
    assert acc.within() == pytest.approx(b2.within_step_r2(y, X, groups), abs=1e-10)
    assert acc.pooled() == pytest.approx(b2.pooled_r2(y, X), abs=1e-10)
    back = b2.R2Acc.from_state(acc.state())
    assert back.within() == acc.within()


@pytest.fixture(scope="module")
def phase(b2, tiny, tmp_path_factory):
    kw = {"vmap": tiny["vmap"], "S": TS, "m": TM, "L": TL}
    a = b2.fit_core(tiny["model"], tiny["train"], tiny["val"], seed=0, **kw)
    fits = {"heads": a["fits"]["heads"], "class_means": a["fits"]["class_means"]}
    out = tmp_path_factory.mktemp("phaseB")
    e = b2.eval_core(
        tiny["model"],
        tiny["eval"],
        fits,
        seed=0,
        label=3000,
        n_tier2=1,
        out_dir=out,
        fits_id="tiny",
        **kw,
    )
    return a, e, out, fits


def test_phase_a_core_fits_decides_on_fit_val_and_passes_its_controls(b2, phase):
    a, _e = phase[:2]
    heads = a["fits"]["heads"]
    for k in ("U@0.9", "C@0.9", "U+@0.0", "C+@0.9", "U3@0.9", "age_U@0.9", "age_C@0.0"):
        assert heads[k]["val_range"] == "FIT_VAL"
    dec = a["decisions"]
    assert set(dec["ref"]) == {"U@0.9", "C@0.9", "U@0.0", "C@0.0"}
    assert dec["delta"][0.0] == dec["delta"][0.9]
    assert set(b2.GATING_CONTRASTS) <= set(dec["sigma"])
    assert "psiU_minus_kind" in dec["sigma"]
    assert a["controls"]["sum_worst"] <= b2.SUM_TOL
    assert a["n"]["n_U"] == 4 * b2.u_rows(TS) and a["n"]["n_C"] == 4 * b2.c_rows(TS, TM)


def test_phase_a_rows_carry_lambda_residual_age_split_and_threads(b2, phase):
    a, _e = phase[:2]
    saved = {
        "heads": a["fits"]["heads"],
        **{k: v for k, v in a.items() if k != "fits"},
        "class_means": a["fits"]["class_means"],
        "age_decodability": a["fits"]["age_decodability"],
    }
    rows = dict(b2.phase_a_rows(3000, 0, saved))
    h = rows["ckpt3000.seed0.head.U@0.9"]
    assert h["resid"] <= b2.SELECTED_RESID and h["lam"] in b2.LAMBDAS
    assert h["grid_edge"] == (h["lam"] in (b2.LAMBDAS[0], b2.LAMBDAS[-1]))
    assert set(rows["ckpt3000.seed0.age_decodability.C"]["r2_split"]) == {
        "i_lt_M",
        "i_ge_M",
    }
    assert "w" not in rows["ckpt3000.seed0.age_decodability.U"]
    assert rows["ckpt3000.seed0.threads"] == saved["threads"] >= 1
    json.dumps(rows)  # every row must be ledger-serialisable


def test_phase_b_core_runs_every_tier_and_streams_e0h(b2, phase):
    _a, e = phase[:2]
    assert set(e) == {"0.9.tier1", "0.9.tier2", "0.0.tier2"}
    t1 = e["0.9.tier1"]
    assert set(t1["counts"]) == set(b2.TIER1)
    assert all(v["all"].shape == (2, 2) for v in t1["counts"].values())
    assert set(e["0.9.tier2"]["counts"]) == set(b2.TIER2_G09)
    assert e["0.9.tier2"]["counts"]["psiU1"]["all"].shape == (1, 2)
    acc = t1["e0h"]
    assert set(acc) == {"U@0.0", "U+@0.0", "C@0.0", "target_D"}
    assert acc["U@0.0"].k == 6 * 2  # six C layers x H = 2
    assert acc["U@0.0"].n == 2 * (TS - TM) * TM
    assert t1["controls"]["logit_control_worst"] <= b2.LOGIT_TOL
    assert t1["e0h_source"] == "prehook_logit"
    for r in e.values():  # F1: no per-eviction record is held in RAM
        assert "logs" not in r


def test_phase_b_summary_reads_ref_and_delta_from_phase_a(b2, phase):
    a, e = phase[:2]
    s = b2.summarise_eval(e, a["decisions"], 0, 3000, n_tier2=1)
    assert set(s) == {"0.9.tier1", "0.9.tier2", "0.0.tier2"}
    t1 = s["0.9.tier1"]
    assert t1["ref"] == {
        "U": a["decisions"]["ref"]["U@0.9"],
        "C": a["decisions"]["ref"]["C@0.9"],
    }
    assert t1["delta"] == a["decisions"]["delta"][0.9]
    assert {"psiU", "psiC", "q2_psiU_minus_kind"} <= set(t1["outcome"])
    assert {"psiU+", "psiC+", "psiU1"} <= set(s["0.9.tier2"]["outcome"])
    for v in t1["outcome"].values():
        assert v["label"].removeprefix("Q2-") in ("WIN", "EQUIV", "LOSS", "UNRESOLVED")
    cls = b2.classification({k: t1 for k in (0, 1, 2)})
    assert cls["row"] in range(1, 7) and "companion" not in cls  # no U+/C+ in Tier 1
    t2 = b2.classification({k: s["0.9.tier2"] for k in (0, 1, 2)})
    assert t2["companion"]["label"] == "non-gating, companion"  # review F6


def test_the_attribution_source_has_row_1s_fields(b2, tiny, phase):
    _a, e, out, _f = phase
    ids = [d.doc_id for d in tiny["eval"]]
    log = b2.unit_logs(out, 0.9, "tier1", ids, "psiU")
    att = b2.attribution(log, TS)
    # review F1: computed online while streaming, equal to the batch computation
    assert e["0.9.tier1"]["attribution"]["psiU"] == att
    assert e["0.9.tier1"]["psi_age_corr"]["psiU"] == b2.psi_age_corr_in_loop(log)
    assert sum(att["age_hist"]) == len(log) == 2 * (TS - TM)
    assert set(att) == {"age_hist", "rank_hist", "kind_status", "margin", "rank_shift"}
    assert all(r["psi"] is not None and len(r["live_ages"]) == TM for r in log)
    corr = b2.psi_age_corr_in_loop(log)
    assert corr["n"] == len(log) * TM


# --------------------------------------------------------------------------- #
# build review F1: EVAL streams per document to disk and resumes
# --------------------------------------------------------------------------- #


def _eval(b2, tiny, fits, out, *, n_tier2=2, fits_id="tiny"):
    kw = {"vmap": tiny["vmap"], "S": TS, "m": TM, "L": TL}
    return b2.eval_core(
        tiny["model"],
        tiny["eval"],
        fits,
        seed=0,
        label=3000,
        n_tier2=n_tier2,
        out_dir=out,
        fits_id=fits_id,
        **kw,
    )


def _same_eval(a, b):
    assert set(a) == set(b)
    for k in a:
        for arm, bb in a[k]["counts"].items():
            for bucket, v in bb.items():
                assert torch.equal(v, b[k]["counts"][arm][bucket]), (k, arm, bucket)
        assert a[k]["attribution"] == b[k]["attribution"]
        assert a[k]["psi_age_corr"] == b[k]["psi_age_corr"]
        assert a[k]["controls"] == b[k]["controls"]
        if a[k]["e0h"] is not None:
            for h, acc in a[k]["e0h"].items():
                other = b[k]["e0h"][h]
                assert acc.n == other.n and torch.equal(acc.xx, other.xx)
                assert acc.within() == other.within()


def test_eval_units_reach_disk_before_the_next_document_runs(
    b2, tiny, phase, tmp_path, monkeypatch
):
    """Review F1 (BLOCKER): a document's unit (counts, controls, E0h statistics and
    its per-eviction logs) is on disk before the next document runs, so the logs of
    a 21 h run never accumulate in RAM."""
    fits = phase[3]
    d0, d1 = (d.doc_id for d in tiny["eval"])
    seen: list[tuple[int, frozenset]] = []

    def snap(doc):
        have = frozenset(str(p.relative_to(tmp_path)) for p in tmp_path.rglob("*.pt.gz"))
        seen.append((doc.doc_id, have))

    real_arm, real_fifo = b2.run_arm, b2.fifo_with_e0h

    def run_arm(model, doc, *a, **k):
        snap(doc)
        return real_arm(model, doc, *a, **k)

    def fifo(model, doc, *a, **k):
        snap(doc)
        return real_fifo(model, doc, *a, **k)

    monkeypatch.setattr(b2, "run_arm", run_arm)
    monkeypatch.setattr(b2, "fifo_with_e0h", fifo)
    e = _eval(b2, tiny, fits, tmp_path)
    tiers = list(b2.tier_plan(3000))
    firsts = [
        have for j, (doc, have) in enumerate(seen) if doc == d1 and seen[j - 1][0] == d0
    ]
    assert len(firsts) == len(tiers)
    for (g, tier), have in zip(tiers, firsts, strict=True):
        want = str(b2.unit_path(tmp_path, g, tier, d0).relative_to(tmp_path))
        assert want in have, f"{g}.{tier}: doc {d0}'s unit not on disk when {d1} ran"
    for r in e.values():
        assert "logs" not in r
    for g, tier in tiers:
        u = b2.load_unit(b2.unit_path(tmp_path, g, tier, d1))
        assert set(u["logs"]) == set(b2.tier_plan(3000)[(g, tier)])


def test_a_restart_skips_completed_units_and_reproduces_the_result(
    b2, tiny, phase, tmp_path, monkeypatch
):
    """Crash safety: a killed EVAL child loses no completed document. A rerun on the
    same directory runs only the units that are missing, and the result is
    identical to an uninterrupted run."""
    fits = phase[3]
    full = _eval(b2, tiny, fits, tmp_path)
    calls: list[int] = []

    def boom(model, doc, *a, **k):
        calls.append(doc.doc_id)
        raise RuntimeError("a completed unit was run again")

    with monkeypatch.context() as mp:
        mp.setattr(b2, "run_arm", boom)
        mp.setattr(b2, "fifo_with_e0h", boom)
        again = _eval(b2, tiny, fits, tmp_path)
    assert calls == []
    _same_eval(full, again)
    assert all(r["n_resumed"] == r["n_docs"] for r in again.values())

    d1 = tiny["eval"][1].doc_id
    b2.unit_path(tmp_path, 0.9, "tier1", d1).unlink()  # the unit a kill interrupted
    (b2.unit_path(tmp_path, 0.9, "tier1", d1).parent / "x.pt.gz.tmp99").write_bytes(
        b"torn write"
    )
    real_arm, real_fifo = b2.run_arm, b2.fifo_with_e0h

    def count_arm(model, doc, *a, **k):
        calls.append(doc.doc_id)
        return real_arm(model, doc, *a, **k)

    def count_fifo(model, doc, *a, **k):
        calls.append(doc.doc_id)
        return real_fifo(model, doc, *a, **k)

    monkeypatch.setattr(b2, "run_arm", count_arm)
    monkeypatch.setattr(b2, "fifo_with_e0h", count_fifo)
    resumed = _eval(b2, tiny, fits, tmp_path)
    assert calls == [d1] * len(b2.TIER1)  # that one unit, every Tier 1 arm, once
    _same_eval(full, resumed)
    assert resumed["0.9.tier1"]["n_resumed"] == 1


def test_a_unit_from_another_configuration_is_refused(b2, tiny, phase, tmp_path):
    """A unit written under other fits (or other code) is never folded into a
    resumed run; the child exits 3 instead of mixing two configurations."""
    fits = phase[3]
    _eval(b2, tiny, fits, tmp_path, n_tier2=1)
    with pytest.raises(b2.ControlFailure, match="another configuration"):
        _eval(b2, tiny, fits, tmp_path, n_tier2=1, fits_id="other fits")


# --------------------------------------------------------------------------- #
# build review F2: `run.py e0h` reaches e0h_main with its arguments and paths
# --------------------------------------------------------------------------- #


def test_e0h_routes_through_main_with_every_argument(b2, monkeypatch):
    got = {}

    def fake(argv):
        got["argv"] = argv
        return 2

    monkeypatch.setattr(b2, "e0h_main", fake)
    argv = ["--fits", "/x", "--checkpoint", "2500", "--eval-dir", "/y"]
    assert b2.main(["e0h", *argv]) == 2
    assert got["argv"] == argv


def test_e0h_defaults_are_the_real_run_dirs(b2):
    a = b2.e0h_parser().parse_args([])
    assert a.fits == b2.ROOT / "runs" / "b2-psi-probe-fit" / "phaseA"
    assert a.fits == b2.ROOT / "runs" / b2.FIT_RUN_ID / "phaseA"
    assert a.eval_dir == b2.ROOT / "runs" / b2.RUN_ID / "phaseB"
    assert a.checkpoint == b2.HEADLINE


# --------------------------------------------------------------------------- #
# build review F3: an E0h control failure is E0h's alone; the log alpha fallback
# --------------------------------------------------------------------------- #


def _e0h_dirs(b2, phase, e, tmp_path):
    """Phase A's heads as a post-fix payload for every seed, and E0h payloads."""
    a = phase[0]
    fits_dir, ev = tmp_path / "fits", tmp_path / "evalB"
    fits_dir.mkdir()
    ev.mkdir()
    heads = {}
    for k, h in a["fits"]["heads"].items():
        heads[k] = dict(h, val_r2_form=b2.R2_FORM)
    for s in b2.SEEDS:
        torch.save({"heads": heads}, fits_dir / f"ckpt3000-seed{s}.pt")
        torch.save(b2.e0h_payload(e), ev / f"ckpt3000-seed{s}.e0h.pt")
    return fits_dir, ev


def test_a_failed_logit_control_is_e0h_exit_3_and_b2_still_completes(
    b2, tiny, phase, tmp_path, monkeypatch
):
    """A1.3 / A1.5: 'a failed control is E0h exit 3'; 'B2's rc covers B2 alone'.
    The EVAL child must finish and record the control, not raise."""
    monkeypatch.setattr(b2, "logit_control", lambda *a, **k: 1.0)
    e = _eval(b2, tiny, phase[3], tmp_path / "units", n_tier2=1)
    assert e["0.9.tier1"]["controls"]["logit_control_worst"] == 1.0
    assert b2.e0h_payload(e)["logit_control_worst"] == 1.0
    s = b2.summarise_eval(e, phase[0]["decisions"], 0, 3000, n_tier2=1)
    assert "psiU" in s["0.9.tier1"]["outcome"]  # B2's own reading exists
    fits_dir, ev = _e0h_dirs(b2, phase, e, tmp_path)
    res = b2.e0h_compute(fits_dir, ev, 3000)
    assert res["rc"] == 3 and "logit control" in res["why"]


def test_the_log_alpha_fallback_when_the_hook_cannot_be_built(
    b2, tiny, phase, tmp_path, monkeypatch
):
    """A1.5: if the pre-hook cannot be built, the within-step primary uses the
    per-token log alpha (exact after within-step demeaning), the pooled secondary is
    DID NOT RUN, and the ledger says `e0h.regressor_source = "log_alpha"`."""
    ref = phase[1]["0.9.tier1"]["e0h"]

    class NoHook:
        def __init__(self, model):
            raise RuntimeError("no pre-hook on this build")

    monkeypatch.setattr(b2, "LogitHook", NoHook)
    e = _eval(b2, tiny, phase[3], tmp_path / "units", n_tier2=1)
    t1 = e["0.9.tier1"]
    assert t1["e0h_source"] == "log_alpha"
    assert t1["controls"]["logit_control_worst"] is None
    for k, acc in t1["e0h"].items():
        assert acc.n == ref[k].n
        assert acc.within() == pytest.approx(ref[k].within(), abs=1e-5), k
    fits_dir, ev = _e0h_dirs(b2, phase, e, tmp_path)
    res = b2.e0h_compute(fits_dir, ev, 3000)
    assert res["e0h.regressor_source"] == "log_alpha"
    assert res["rc"] == 2  # unratified, and not DID NOT RUN
    for s in b2.SEEDS:
        for v in res["e0h.per_seed"][s].values():
            assert v["pooled"] is None and v["within"] is not None


def test_the_prehook_source_is_recorded_when_the_hook_builds(b2, tiny, phase, tmp_path):
    e = phase[1]
    fits_dir, ev = _e0h_dirs(b2, phase, e, tmp_path)
    res = b2.e0h_compute(fits_dir, ev, 3000)
    assert res["e0h.regressor_source"] == "prehook_logit"
    assert res["rc"] == 2
    assert all(
        v["pooled"] is not None for s in b2.SEEDS for v in res["e0h.per_seed"][s].values()
    )


# --------------------------------------------------------------------------- #
# build review F4: the wiring of the gating decision, on hand-built counts
# --------------------------------------------------------------------------- #

_D = 400


def _bern(p: float, seed: int, n: int = 10) -> torch.Tensor:
    g = torch.Generator().manual_seed(seed)
    c = (torch.rand(_D, n, generator=g) < p).sum(1)
    return torch.stack([torch.full((_D,), n), c], 1)


def _arms(b2, spec: dict, base: int = 0) -> dict:
    """arm -> bucket -> [D, 2]; `spec[arm]` is p for every bucket or a dict with
    an 'all' default and per-bucket overrides."""
    out = {}
    for a_i, (arm, ps) in enumerate(spec.items()):
        ps = ps if isinstance(ps, dict) else {"all": ps}
        out[arm] = {
            b: _bern(ps.get(b, ps["all"]), base + 97 * a_i + b_i)
            for b_i, b in enumerate(b2.BUCKETS)
        }
    return out


def _labels(res):
    return {k: v["label"] for k, v in res["outcome"].items()}


def test_win_needs_non_inferiority_on_gap_2_to_m(b2):
    """§9.5: WIN needs the gap_2_to_M CI lower bound above -δ. Here ψ̂-U is far
    ahead on all queries and far behind on gap_2_to_M; ψ̂-C is ahead on both."""
    rnd = {f"random{k}": 0.5 for k in range(5)}
    c = _arms(
        b2,
        {
            "psiU": {"all": 0.9, "gap_2_to_M": 0.2},
            "psiC": 0.9,
            "fifo": {"all": 0.7, "gap_2_to_M": 0.8},
            "ageU": 0.5,
            "ageC": 0.5,
            **rnd,
            "kind": 0.5,
        },
    )
    res = b2.outcomes_for(c, {"U": "fifo", "C": "fifo"}, 0.05, seed=0)
    lab = _labels(res)
    assert lab["psiU"] == "UNRESOLVED"
    assert lab["psiC"] == "WIN"
    assert res["boot"]["gap_2_to_M"]["psiU_minus_refU"]["lo"] < -0.05
    assert res["boot"]["all"]["psiU_minus_refU"]["lo"] > 0


def test_win_needs_the_random_floor_not_the_ref(b2):
    """§9.5: WIN's last clause is the ψ̂ - random CI lower bound > 0."""
    c = _arms(
        b2,
        {
            "psiU": 0.9,
            "psiC": 0.9,
            "fifo": 0.7,
            "ageU": 0.5,
            "ageC": 0.5,
            **{f"random{k}": 0.95 for k in range(5)},
            "kind": 0.5,
        },
        base=5,
    )
    res = b2.outcomes_for(c, {"U": "fifo", "C": "fifo"}, 0.05, seed=1)
    assert res["boot"]["all"]["psiU_minus_refU"]["lo"] > 0
    assert res["boot"]["all"]["psiU_minus_random"]["lo"] < 0
    assert _labels(res)["psiU"] == "UNRESOLVED"


def test_loss_equiv_and_the_ref_arm_follow_ref(b2):
    """LOSS against ref = age reads ageU, not FIFO; an arm identical to its ref is
    EQUIV."""
    c = _arms(
        b2,
        {
            "psiU": 0.5,
            "fifo": 0.3,
            "ageU": 0.8,
            "ageC": 0.5,
            **{f"random{k}": 0.4 for k in range(5)},
            "kind": 0.5,
        },
        base=11,
    )
    c["psiC"] = {b: v.clone() for b, v in c["fifo"].items()}
    res = b2.outcomes_for(c, {"U": "age", "C": "fifo"}, 0.05, seed=2)
    lab = _labels(res)
    assert lab["psiU"] == "LOSS" and lab["psiC"] == "EQUIV"
    pu = res["boot"]["all"]["psiU_minus_refU"]["point"]
    assert pu == pytest.approx(
        b2.pooled_acc(c["psiU"]["all"]) - b2.pooled_acc(c["ageU"]["all"])
    )


def test_val_decisions_delta_is_a_quarter_of_oracle_minus_fifo(b2):
    """§9.3: δ = 0.25 (acc_oracle - acc_FIFO) on FIT_VAL; gamma = 0 reuses it (A1.11);
    ref per (arm, gamma) is the better of FIFO and its age head."""
    arms09 = _arms(
        b2,
        {
            "psiU": 0.6,
            "psiC": 0.62,
            "fifo": 0.7,
            "ageU": 0.78,
            "ageC": 0.62,
            **{f"random{k}": 0.5 + 0.02 * k for k in range(5)},
            "oracle": 0.9,
            "kind": 0.65,
        },
        base=21,
    )
    arms0 = _arms(b2, {"fifo": 0.7, "ageU": 0.6, "ageC": 0.75}, base=41)
    arms0["fifo"] = arms09["fifo"]
    ids = list(range(936000, 936000 + _D))
    dec = b2.val_decisions({0.9: {"counts": arms09}, 0.0: {"counts": arms0}}, 0, ids)
    acc = {a: b2.pooled_acc(v["all"]) for a, v in arms09.items()}
    want = 0.25 * (acc["oracle"] - acc["fifo"])
    assert dec["delta"][0.9] == pytest.approx(want, abs=1e-15)
    assert dec["delta"][0.0] == dec["delta"][0.9]
    assert dec["ref"] == {
        "U@0.9": "age",
        "C@0.9": "fifo",
        "U@0.0": "fifo",
        "C@0.0": "age",
    }
    assert set(b2.GATING_CONTRASTS) <= set(dec["sigma"])


def test_the_gamma_zero_contrasts_use_the_gamma_zero_ref(b2):
    """§9.8: gamma = 0 uses its own ref (and δ from gamma = 0.9, A1.11)."""
    names09 = (*b2.TIER1, *b2.TIER2_G09)
    spec09 = {a: 0.6 for a in names09}
    t09 = _arms(b2, spec09, base=51)
    spec0 = {a: 0.6 for a in b2.TIER2_G0}
    spec0["ageU"] = 0.9
    spec0["ageC"] = 0.9
    t0 = _arms(b2, spec0, base=71)
    t0["psiU"] = {b: v.clone() for b, v in t09["fifo"].items()}  # = FIFO exactly
    ev = {"0.9.tier2": {"counts": t09}, "0.0.tier2": {"counts": t0}}
    dec = {
        "ref": {"U@0.9": "fifo", "C@0.9": "fifo", "U@0.0": "age", "C@0.0": "age"},
        "delta": {0.9: 0.05, 0.0: 0.05},
    }
    s = b2.summarise_eval(ev, dec, 0, 2500, n_tier2=_D)
    assert s["0.0.tier2"]["ref"] == {"U": "age", "C": "age"}
    assert s["0.9.tier2"]["ref"] == {"U": "fifo", "C": "fifo"}
    assert s["0.0.tier2"]["outcome"]["psiU"]["label"] == "LOSS"  # vs ageU, not FIFO


def test_the_bootstrap_is_seeded_and_leaves_the_global_rng_alone(b2):
    """§9.2: `torch.Generator(20260927 + seed)`; the global RNG is never drawn."""
    c = _arms(b2, {"a": 0.7, "b": 0.6}, base=81)
    per = {k: v["all"] for k, v in c.items()}
    con = {"a_minus_b": ("a", "b")}
    torch.manual_seed(1)
    st = torch.get_rng_state()
    x = b2.paired_bootstrap(per, con, seed=3, n_boot=300)
    assert torch.equal(torch.get_rng_state(), st)
    torch.manual_seed(999)
    assert b2.paired_bootstrap(per, con, seed=3, n_boot=300) == x
    assert b2.paired_bootstrap(per, con, seed=4, n_boot=300) != x


def test_e0h_rows_pair_each_slot_with_its_own_sentence(b2, tiny, phase):
    """§10 / A1.4: at full-memory step t, FIFO slot j holds sentence t - m + j;
    its E0h row carries ψ̂(s_{t-m+j}, c_t) and D[t, t-m+j], recomputed here from an
    independent capture of the same document."""
    a = phase[0]
    kw = {"vmap": tiny["vmap"], "S": TS, "m": TM, "L": TL}
    doc = tiny["eval"][0]
    heads = {k: a["fits"]["heads"][k]["w"] for k in b2.E0H_HEADS}
    rows = b2.fifo_with_e0h(tiny["model"], doc, heads, **kw)["e0h"]
    cap = b2.capture_doc(tiny["model"], doc, **kw)
    want = {k: [] for k in heads}
    want_d, want_g = [], []
    for t in range(TM, TS):
        for j in range(TM):
            i = t - TM + j
            f = b2.bilinear_features(cap.gest[i].unsqueeze(0), cap.ctx[t].unsqueeze(0))
            for k, w in heads.items():
                want[k].append(float((f @ w.to(torch.float64))[0]))
            want_d.append(float(cap.D[0][t, i]))
            want_g.append(t)
    for k in heads:
        got = rows[k].tolist()
        assert got == pytest.approx(want[k], abs=1e-9), k
        assert len(set(round(x, 9) for x in got[:TM])) == TM  # slots are distinguishable
    assert rows[b2.E0H_TARGET].tolist() == pytest.approx(want_d, abs=1e-12)
    assert rows["groups"].tolist() == want_g


# --------------------------------------------------------------------------- #
# build review F5, F6, F10
# --------------------------------------------------------------------------- #


def test_a_child_rc_1_is_a_parent_fail_not_a_did_not_run(b2):
    assert b2.parent_rc({"a": 0, "b": 0}, t0_ok=True) == b2.Exit.OK
    assert b2.parent_rc({"a": 0, "b": 1}, t0_ok=True) == b2.Exit.FAIL
    assert b2.parent_rc({"a": 3, "b": 1}, t0_ok=True) == b2.Exit.FAIL
    assert b2.parent_rc({"a": 3, "b": 0}, t0_ok=True) == b2.Exit.DID_NOT_RUN
    assert b2.parent_rc({"a": 0}, t0_ok=False) == b2.Exit.DID_NOT_RUN


def test_a_missing_t0_record_is_a_failed_check_not_a_crash(b2, tmp_path):
    r = b2.t0_checked(tmp_path / "absent" / "RESTORE.md")
    assert r["ok"] is False and "no T0 record" in r["why"]


def _summ(u, c, up=None, cp=None):
    out = {"psiU": {"label": u}, "psiC": {"label": c}}
    if up is not None:
        out["psiU+"] = {"label": up}
        out["psiC+"] = {"label": cp}
    return {"outcome": out}


def test_every_summary_is_classified_and_a_checkpoint_disagreement_is_moving(b2):
    """§9.6 (ckpt2500 reported, 'moving' when the classes differ), §9.8 (gamma = 0
    secondary), A1.2 (the (U⁺, C⁺) companion, non-gating)."""
    per = {
        3000: {
            s: {
                "0.9.tier1": _summ("WIN", "WIN"),
                "0.9.tier2": _summ("WIN", "WIN", "LOSS", "EQUIV"),
                "0.0.tier2": _summ("EQUIV", "EQUIV"),
            }
            for s in b2.SEEDS
        },
        2500: {
            s: {"0.9.tier2": _summ("EQUIV", "EQUIV"), "0.0.tier2": _summ("LOSS", "WIN")}
            for s in b2.SEEDS
        },
    }
    out = b2.classify_all(per)
    assert out["headline"]["class"] == "NOT RULED OUT, CENSORED"
    assert out["headline"]["gating"] is True
    assert out["companion"]["class"] == "HARMFUL"
    assert out["companion"]["label"] == "non-gating, companion"
    assert out["ckpt2500"]["class"] == "NOT LEARNABLE, offline"
    assert out["moving"] is True
    assert out["gamma0_secondary"][3000]["class"] == "NOT LEARNABLE, offline"
    assert out["gamma0_secondary"][2500]["class"] == "HARMFUL"
    assert out["gamma0_secondary"][3000]["label"] == "secondary"
    same = {
        3000: per[3000],
        2500: {
            s: dict(per[2500][s], **{"0.9.tier2": _summ("WIN", "WIN")}) for s in b2.SEEDS
        },
    }
    assert b2.classify_all(same)["moving"] is False


def test_only_the_named_ruling_ratifies_e0h(b2, tmp_path, monkeypatch):
    """Review F10: a ruling that merely mentions e0h (for example one rejecting the
    thresholds) does not ratify them; only the ruling named in E0H_RULING does."""
    rul = tmp_path / "docs" / "owner" / "rulings"
    rul.mkdir(parents=True)
    (rul / "R-2026-10-01-e0h-thresholds-rejected.md").write_text("rejected\n")
    assert b2.E0H_RULING is None
    assert b2.e0h_ratified(tmp_path) is False
    monkeypatch.setattr(b2, "E0H_RULING", "docs/owner/rulings/R-2026-10-02-e0h.md")
    assert b2.e0h_ratified(tmp_path) is False  # named, but absent
    (rul / "R-2026-10-02-e0h.md").write_text("ratified\n")
    assert b2.e0h_ratified(tmp_path) is True


def test_n_e_is_the_preregs_tbd_3(b2):
    """PREREG "Addendum: TBD-3, N_E": the floor 1024 binds."""
    assert b2.N_E == 1024 == b2.N_E_MIN
