"""The researcher outbox: one file per run, and a generated index.

Usage::

    PYTHONPATH=scripts .venv/bin/python -m orchestrator.outbox new <run_id>
    PYTHONPATH=scripts .venv/bin/python -m orchestrator.outbox check <run_id>
    PYTHONPATH=scripts .venv/bin/python -m orchestrator.outbox index

**Why one file per run (blinding).** Until 2026-09-22 every researcher prepended its
report to one shared file, `.orchestrator/outbox/researcher.md`. That file is the
channel through which the 09-21 decisive researcher saw S0-03's numbers before it
had registered anything against them. Each run now writes
`.orchestrator/outbox/<run_id>.md` and nothing else; the researcher's PreToolUse hook
(`orchestrator.hooks`) refuses reads of any other file in the directory, and
`researcher.md` becomes a table **generated** from the per-run files by ``index``.

``new`` copies the report template **out of** `.claude/agents/rsr-researcher.md`
("## Your report") rather than keeping a second copy here: a paraphrase is a second,
divergent copy, and every copy rots (`rsr-manager.md`, "Never paraphrase the brief").

``check`` is the same validation the researcher's Stop hook runs: a report is
complete only with a `status:` in the protocol and the four required fields filled
(`none` written out, never left as the template's `<...>` placeholder).

The first ``index`` over a hand-written (prepend-only) `researcher.md` moves it to
`_legacy-researcher.md` instead of overwriting it -- the old reports are the record
of nights 09-18 through 09-21.

Exit codes (`rsr.exit_codes`): ``new`` refuses an existing file or a bad run id with
`3`; ``check`` exits `1` on an incomplete report and `3` when there is no report.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO / "src"))

from rsr.exit_codes import (  # noqa: E402
    ArgumentParser,
    Exit,
    did_not_run,
    run_main,
    status,
)

OUTBOX_REL = Path(".orchestrator") / "outbox"
INDEX_NAME = "researcher.md"
LEGACY_NAME = "_legacy-researcher.md"
ROLE_FILE_REL = Path(".claude") / "agents" / "rsr-researcher.md"
GENERATED_MARKER = "<!-- GENERATED by orchestrator.outbox index -- do not edit. -->"

STATUSES = ("RETURNED", "BLOCKED", "CRASHED", "QUESTION")
REQUIRED_FIELDS = (
    "BRIEF ERRORS",
    "UNANSWERED BY THE BRIEF",
    "BELIEVED, NOT VERIFIED",
    "NEXT (proposed, not decided)",
)
#: Every field name the template defines. A line starting with one of these (at
#: column 0, followed by ':') opens a field; anything else continues the last one.
KNOWN_FIELDS = (
    "status",
    "run_id",
    "updated",
    "provenance",
    "manifest",
    "falsifier",
    "expected",
    "observed",
    "gates",
    "ledger",
    "numbers",
    *REQUIRED_FIELDS,
)

_RUN_ID_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}")


def valid_run_id(run_id: str) -> bool:
    """A run id is a file-name-safe token, and never one of the reserved names."""
    return bool(_RUN_ID_RE.fullmatch(run_id)) and f"{run_id}.md" not in (
        INDEX_NAME,
        LEGACY_NAME,
    )


def outbox_dir(root: Path) -> Path:
    return root / OUTBOX_REL


def report_path(root: Path, run_id: str) -> Path:
    return outbox_dir(root) / f"{run_id}.md"


# --------------------------------------------------------------------------- #
# Parsing and validation
# --------------------------------------------------------------------------- #


def parse_fields(text: str) -> dict[str, str]:
    """`{field: content}` for the known fields. Content is the rest of the opening
    line plus every continuation line until the next known field. The first
    occurrence of a field wins (a report is one header, not a history)."""
    fields: dict[str, list[str]] = {}
    current: str | None = None
    for line in text.splitlines():
        opened = None
        for name in KNOWN_FIELDS:
            if line.startswith(name + ":"):
                opened = name
                break
        if opened is not None:
            if opened in fields:
                current = None  # a second copy of a field: ignore it and its body
                continue
            current = opened
            fields[current] = [line[len(opened) + 1 :]]
        elif current is not None:
            fields[current].append(line)
    return {k: "\n".join(v).strip() for k, v in fields.items()}


def _is_placeholder(content: str) -> bool:
    """The template's own text: `<list>`, `<what you would run, and why>`, ..."""
    return content.startswith("<")


def validate_report(text: str, run_id: str | None = None) -> list[str]:
    """Every reason `text` is not a complete report. Empty list == complete."""
    problems = []
    fields = parse_fields(text)
    st = fields.get("status", "")
    first = st.split()[0] if st.split() else ""
    if "status" not in fields:
        problems.append("no `status:` line")
    elif first not in STATUSES or "|" in st.split("\n")[0]:
        # `|` : the template's own line (`RETURNED | BLOCKED | ...`), unchosen.
        problems.append(f"`status: {st[:40]}` is not exactly one of {STATUSES}")
    if run_id is not None:
        rid = fields.get("run_id", "")
        if rid.split()[:1] != [run_id]:
            problems.append(f"`run_id:` is {rid[:60]!r}, not {run_id!r}")
    for name in REQUIRED_FIELDS:
        if name not in fields:
            problems.append(f"required field `{name}:` is missing")
        elif not fields[name]:
            problems.append(f"`{name}:` is empty -- write `none` out")
        elif _is_placeholder(fields[name]):
            problems.append(f"`{name}:` is still the template placeholder")
    return problems


# --------------------------------------------------------------------------- #
# new
# --------------------------------------------------------------------------- #


def template_from_role(role_text: str) -> str:
    """The report template: the code blocks under `## Your report`, joined."""
    try:
        section = role_text.split("## Your report", 1)[1]
    except IndexError:
        raise ValueError("rsr-researcher.md has no '## Your report' section") from None
    section = re.split(r"\n## ", section, maxsplit=1)[0]
    blocks = re.findall(r"```[^\n]*\n(.*?)```", section, flags=re.S)
    if not blocks:
        raise ValueError("rsr-researcher.md '## Your report' has no template block")
    return "\n".join(b.rstrip("\n") for b in blocks) + "\n"


def render_new(role_text: str, run_id: str) -> str:
    body = template_from_role(role_text)
    return re.sub(r"(?m)^run_id: .*$", f"run_id: {run_id}", body, count=1)


def cmd_new(root: Path, run_id: str) -> Exit:
    if not valid_run_id(run_id):
        return did_not_run(f"{run_id!r} is not a valid run id (or is reserved)")
    path = report_path(root, run_id)
    if path.exists():
        return did_not_run(f"{path} already exists; one run, one report file")
    role = root / ROLE_FILE_REL
    if not role.is_file():
        return did_not_run(f"no role file at {role}; the template lives there")
    text = render_new(role.read_text(), run_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(path)
    return Exit.OK


def cmd_check(root: Path, run_id: str) -> Exit:
    path = report_path(root, run_id)
    if not path.is_file():
        return did_not_run(f"no report at {path}")
    problems = validate_report(path.read_text(), run_id)
    for p in problems:
        print(f"INCOMPLETE: {p}")
    if problems:
        return Exit.FAIL
    print(f"OK: {path} is complete")
    return Exit.OK


# --------------------------------------------------------------------------- #
# index
# --------------------------------------------------------------------------- #


def run_files(root: Path) -> list[Path]:
    d = outbox_dir(root)
    if not d.is_dir():
        return []
    return sorted(
        p for p in d.glob("*.md") if p.name != INDEX_NAME and not p.name.startswith("_")
    )


def render_index(root: Path) -> str:
    rows = []
    for p in run_files(root):
        f = parse_fields(p.read_text())
        st = f.get("status", "").split()
        rows.append(
            (
                f.get("updated", "").split("\n")[0].strip(),
                p.stem,
                st[0] if st else "(no status)",
                p.name,
            )
        )
    rows.sort(key=lambda r: (r[0], r[1]), reverse=True)
    out = [
        GENERATED_MARKER,
        "",
        "# Researcher outbox -- index",
        "",
        "Regenerate with `PYTHONPATH=scripts .venv/bin/python -m orchestrator.outbox "
        "index`. One report per run lives beside this file as `<run_id>.md` "
        "(blinding: a researcher's hook lets it read only its own). Newest first.",
        "",
        "| updated | run_id | status | report |",
        "|---|---|---|---|",
    ]
    out += [
        f"| {u or '-'} | {rid} | {s} | [{name}]({name}) |" for u, rid, s, name in rows
    ]
    if not rows:
        out.append("| - | (no per-run reports yet) | - | - |")
    if (outbox_dir(root) / LEGACY_NAME).exists():
        out += [
            "",
            f"Reports filed before per-run files (prepend-only, 2026-09-18 .. "
            f"2026-09-21): [{LEGACY_NAME}]({LEGACY_NAME}).",
        ]
    return "\n".join(out) + "\n"


def cmd_index(root: Path) -> Exit:
    d = outbox_dir(root)
    d.mkdir(parents=True, exist_ok=True)
    index = d / INDEX_NAME
    if index.exists() and not index.read_text().startswith(GENERATED_MARKER):
        legacy = d / LEGACY_NAME
        if legacy.exists():
            return did_not_run(
                f"{index} is hand-written and {legacy} already exists; refusing to "
                f"overwrite either"
            )
        os.replace(index, legacy)
        print(f"moved the hand-written {INDEX_NAME} to {LEGACY_NAME}")
    index.write_text(render_index(root))
    print(f"{index}: {len(run_files(root))} run report(s)")
    return Exit.OK


def main() -> Exit:
    ap = ArgumentParser(prog="orchestrator.outbox")
    ap.add_argument("--root", type=Path, default=Path.cwd(), help="repo root")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p_new = sub.add_parser("new")
    p_new.add_argument("run_id")
    p_check = sub.add_parser("check")
    p_check.add_argument("run_id")
    sub.add_parser("index")
    args = ap.parse_args()
    root = args.root.resolve()
    if args.cmd == "new":
        return status(cmd_new(root, args.run_id))
    if args.cmd == "check":
        return status(cmd_check(root, args.run_id))
    return status(cmd_index(root))


if __name__ == "__main__":
    run_main(main)
